### ISSUE TITLE
PropertyChanging and PropertyChanged not fired

### ISSUE THREAD

**Issue by AgPeHaJIuH1** [reactiveui/ReactiveUI#2693] opened 2021-03-02 20:04 UTC
**Describe the bug**
PropertyChanging and PropertyChanged don't fire if you just inherit IReactiveObject.
But surprisingly, WhenAnyValue works!

**Steps To Reproduce**
  ```
  class Test : IReactiveObject
    {
        public event PropertyChangedEventHandler PropertyChanged;
        public event PropertyChangingEventHandler PropertyChanging;
        public void RaisePropertyChanging(PropertyChangingEventArgs args)
        {
            //Not fired
            PropertyChanging?.Invoke(this, args);
        }
        public void RaisePropertyChanged(PropertyChangedEventArgs args)
        {
            //Not fired
            PropertyChanged?.Invoke(this, args);
        }

        private string _testProp;
        public string TestProp
        {
            get => _testProp;
            set => this.RaiseAndSetIfChanged(ref _testProp, value);
        }
    }

    public partial class App : Application
    {
        public App()
        {
            Test test = new Test();
            test.PropertyChanged += (sender, args) =>
            {
                //Not fired
            };

            test.WhenAnyPropertyChanged(nameof(Test.TestProp))
                .Subscribe(_ =>
                {
                    //Not fired
                });

            test.WhenAnyValue(q => q.TestProp)
                .Subscribe(_ =>
                {
                    //FIRED!!!
                });

            test.TestProp = "111";
            test.TestProp = "222";
        }

        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);
        }
    }
```

**Environment**
- OS:       Windows 
- Version   10

**Additional context**
This is a WPF project.

ReactiveUI: 13.1.1
ReactiveUI.WPF: 13.1.1

**Comment by AgPeHaJIuH1** [comment] 2021-03-02 20:08
Oh, sorry, I see that the same problem has already been opened earlier. =(

**Comment by RLittlesII** [comment] 2021-03-05 17:33
Related To: https://github.com/reactiveui/ReactiveUI/issues/2594

**Comment by glennawatson** [comment] 2021-03-12 00:12
I'll see about doing a point release for this bug on the weekend, closing this as a duplicate of #2594 for the moment

**Closed by glennawatson** 2021-03-12 00:12 UTC
Labels: bug
