### ISSUE TITLE
[BUG] Memory leak without disposing 'WhenActivated' returned value 

### ISSUE THREAD

**Issue by parisq** [reactiveui/ReactiveUI#2935] opened 2021-09-20 17:04 UTC
**Describe the bug**
Hi, I found a memory leak by using WhenActivated in a view.
If we don't dispose the disposable returned by WhenActivated, it seems that the view and their elements are kept in memory.

With memory leak
```
public BookView()
{
  InitializeComponent();
  this.WhenActivated(d =>  {  ... });
}
```

Without

```
public BookView()
{
  InitializeComponent();
  IDisposable l_disp = Disposable.Empty;;
  this.WhenActivated(d =>
  {
    ...
    d(l_disp);
  });
}
```

**Steps To Reproduce**
1. Run my simple application WPAFApplication.exe
2. click a lot of time on "add" button to add objects in the list.
2.1 Left list is the base case with a memory leak
2.2 Right list is the 'fixed way' by disposing WhenActivated  return
3. then click on clear button
4. make a snapshot with dot memory

**Expected behaviour**
We shouldn't have any view model retained by their views.

**Screenshots**
![image](https://user-images.githubusercontent.com/86288519/134039455-fb162b8b-d468-474c-852b-bc065d5427be.png)
![image](https://user-images.githubusercontent.com/86288519/134039662-ecd5e854-ed66-444e-bbd0-ee8e2cec32c9.png)

**Environment**

- OS:       W10
- ReactiveUI Version:    16.2.6 and 16.2.1

**Additional context**
Have a good day :)

[WpfApplication.zip](https://github.com/reactiveui/ReactiveUI/files/7197279/WpfApplication.zip)

**Comment by lippling** [comment] 2021-09-23 11:38
I have exactly the same problem.
I thought it was problem with my code, but when I applied this workaround, my leaks were gone.
Is this something that will be fixed?

**Comment by lippling** [comment] 2021-09-23 14:12
Ok, I did some further testing:

10.5.30-14.1.1: no memory leaks
>= 14.2.1: memory leaks

Maybe it has something to do with https://github.com/reactiveui/ReactiveUI/pull/2793.

**Comment by glennawatson** [comment] 2021-09-23 16:36
Thanks for the detective work will have to look into it on the weekend.

**Comment by TSSoftware** [comment] 2021-10-03 06:59
I have a quite similar problem. I use finalizer during debug to show an info line when garbage collection takes place for an object. The last version finalizers were called was 13.3.2.

**Comment by gerardo-lijs** [comment] 2021-10-11 07:11
I noticed this when upgrading WPF ReactiveUI a couple of months ago. I tested with 14.1.1 it works and it doesn't with 14.2.1, so it's narrowed to changes between those two specific versions. I created this demo sample to check it out after talking about this in Slack channel. Last month I was busy with family issues so I couldn't follow up on this.

https://github.com/gerardo-lijs/ReactiveUI.Demo_DisposableLeak

. There was an specific PR between 14.1.1 and 14.2.1 that I think might be the cause, but I'm not familiar with ReactiveUI internal code so can't be sure.  https://github.com/reactiveui/ReactiveUI/pull/2793

Maybe @ChrisPulman can help here.

**Closed** 2021-10-30 08:24 UTC
Labels: bug

**Comment by gerardo-lijs** [comment] 2021-11-13 16:17
@glennawatson thanks for working on this! I updated to ReactiveUI 16.3.10 and now it's not leaking on the main window but still leaks in the DetailViewModels. You can take a look, difference between main branch (13.2.2), reaciveui-14-3-1 branch and the new one reactiveui-16.3.10 branch.

Let me know if you need more details and happy to help in any way. Also, maybe other users who reported this (like @hutterm or @parisq) can confirm part of the leak is still there.
