### ISSUE TITLE
Broken link in PlatformRegistrations

### ISSUE THREAD

**Issue by wldevries** [reactiveui/ReactiveUI#2059] opened 2019-05-31 10:21 UTC
Link in `PlatformRegistrations` is incorrect.

**Describe the bug**
The exception message mentions the link https://reactiveui.net/docs/getting-started/installation/nuget-packages which is broken.

It should probably link to: https://reactiveui.net/docs/getting-started/installation/

**Comment by glennawatson** [comment] 2019-05-31 10:33
Duplicate of https://github.com/reactiveui/ReactiveUI/issues/2053

**Closed by glennawatson** 2019-05-31 10:33 UTC
Labels: bug
