### ISSUE TITLE
ReactiveList and/or DerivedCollection not updating ListView in View in Xamarin.Forms Unified API

### ISSUE THREAD

**Issue by michaeldimoudis** [reactiveui/ReactiveUI#855] opened 2015-05-15 13:37 UTC
Hi

I can not get a ReactiveList and/or DerivedCollection to update a ListView in the View, even though these lists/models actually DO get updated. The issue is in Xamarin.Forms Unified API.

I have an old Xamarin.Forms project which isn't converted to Unified API with latest updated nuget packages ie: ReactiveUI 6.5.0 and Xamarin.Forms 1.4.2 and it is working. Converting it to Unified API and retargeting the nuget packages the ReactiveList and/or DerivedCollection does not update the View.

Heeeelp pleaseee :(

**Comment by armintelker** [comment] 2015-05-22 13:37
Here is a example app that have maybe the same issue. 
https://github.com/rebuy-de/reactivelist-xamarin

If you try to remove items from a `ListView` it works in some cases and on some cases it don't work. 
This strange behavior you can see in the [example.mov](https://github.com/rebuy-de/reactivelist-xamarin/blob/master/example.mov) video.

**Comment by armintelker** [comment] 2015-05-26 10:05
We have a solution for our application:

```C#
public class ReactiveObservableCollection<T> : ReactiveList<T> {

    public ObservableCollection<T> ObservableCollection { private set; get; }

    public ReactiveObservableCollection()
    {
        this.ObservableCollection = new ObservableCollection<T>();
        ItemsAdded.Subscribe(ObservableCollection.Add);
        ItemsRemoved.Subscribe((x) => ObservableCollection.Remove(x));
    }
}
```

```C#
public class ViewModel : ReactiveObject {
    [Reactive]
    public ReactiveObservableCollection<Item> Items { set; get; }

    public ViewModel() 
    {
         Items = new ReactiveObservableCollection<Item>() {
             ChangeTrackingEnabled = true
         };
    }
}
```

```XAML
 <ListView ItemsSource="{Binding Items.ObservableCollection}" />
```

**Comment by michaeldimoudis** [comment] 2015-05-30 03:13
Thanks, but unfortunately this did not fix my issue :(
I'm also using IReactiveDerivedList maybe that is why?

**Comment by megafinz** [comment] 2016-12-13 13:29
Any updates on that? Having the same issue. ReactiveList doesn't trigger any ListView updates although in debug I can see that ItemsSource does actually change. If I swap ReactiveList with ObservableCollection everything works just fine.

**Comment by jamilgeor** [comment] 2017-02-17 04:41
I found the following workaround for this issue...

The following fails:
```csharp
MyList = new ReactiveList<string>();
MyList.Add("Item 1");
MyList.Add("Item 2");
```

And this passes:
```csharp
MyList = new ReactiveList<string>(new string [] { "Item 1" });
MyList.Add("Item 2");
```
When initializing a new instance of ReactiveList with a initialContents parameter, the list starts behaving correctly.  If you initialize without initialContents parameter it does not work as expected.

**Comment by kentcb** [comment] 2017-02-17 04:52
Pretty sure this is a duplicate of #806.

**Comment by jamilgeor** [comment] 2017-02-17 09:27
Sorry, yeah my problem is a duplicate of #806

**Closed** 2017-09-01 09:47 UTC
Labels: reactiveui-core, waiting-for-response-or-contribution, xamarin-forms
