### ISSUE TITLE
[BUG] containing type does not implement interface 'IComponentConnector' when use ReactiveWindow

### ISSUE THREAD

**Issue by yuzifu** [reactiveui/ReactiveUI#3002] opened 2021-11-06 03:45 UTC
**Describe the bug**
ReactiveWindow and ReactiveUserControl can't work in .net 6 wpf application.

**Steps To Reproduce**

1, Create .net 6 wpf application, and install reactiveui nuget packages.

2, Edit MainWindow.xaml as follows:
```
<rxui:ReactiveWindow x:Class="VDS.MainWindow"
        x:TypeArguments="local:MainWindowViewModel"
        xmlns:rxui="http://reactiveui.net"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:VDS"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>

    </Grid>
</rxui:ReactiveWindow>
```

3, Edit MainWindow.xaml.cs as follows:
```
namespace VDS
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : ReactiveWindow<MainWindowViewModel>
    {
        public MainWindow()
        {
            InitializeComponent();
        }
    }
}
```

4, Add class MainWindowViewModel as follows:
```
namespace VDS
{
    public class MainWindowViewModel : ReactiveObject, IScreen
    {
        public RoutingState Router { get; }

        public MainWindowViewModel()
        {
            Router = new RoutingState();

            Locator.CurrentMutable.RegisterViewsForViewModels(Assembly.GetCallingAssembly());
        }
    }
}
```

**Expected behaviour**
The following error is prompted when VS compiles the project：
```
Error XDG0008 The name "ReactiveWindow" does not exist in the namespace "http://reactiveui.net".
Error CS0540 'MainWindow.IComponentConnector.Connect(int, object)': containing type does not implement interface 'IComponentConnector'
Error XDG0008 The name "MainWindowViewModel" does not exist in the namespace "clr-namespace:VDS".
```

**Environment**
- OS:       Win 11
- Version   .net 6
- Device:   PC
- ReactiveUI Version:    16.3.10

**Comment by yuzifu** [comment] 2021-11-06 10:04
I found the cause of the problem:

The configuration item 'Nullable' in project properties must be set disabled

Does this mean that I can't use the 'Nullable' feature if I want to use ReactiveWindow?

**Comment by glennawatson** [comment] 2021-11-06 10:12
Try referencing the DLL with a clr namespace directly rather than the reactiveui.net namespace to see if that solves your issue.

**Comment by yuzifu** [comment] 2021-11-06 10:58
> Try referencing the DLL with a clr namespace directly rather than the reactiveui.net namespace to see if that solves your issue.

Thank you for your reply.

I replaced 
```
xmlns:rxui="http://reactiveui.net"
```
 with 
```
xmlns:rxui="clr-namespace:ReactiveUI;assembly=ReactiveUI.Wpf"
```

Nullable still needs to be disabled for workers

**Comment by glennawatson** [comment] 2021-11-06 11:20
Ok

Try removing 
 `: ReactiveWindow<MainWindowViewModel>`
  
From

`public partial class MainWindow : ReactiveWindow<MainWindowViewModel>`

You don't need to provide the class override when providing it in the xaml. 

Want to rule out it's a nullability issue

**Comment by yuzifu** [comment] 2021-11-06 12:25
Thank you very much. After I cancel inheriting reactivewindow in xaml.cs, vs can successfully compile the project.

Is this a bug, or is it designed to work like this?

> Ok
> 
> Try removing `: ReactiveWindow<MainWindowViewModel>`
> 
> From
> 
> `public partial class MainWindow : ReactiveWindow<MainWindowViewModel>`
> 
> You don't need to provide the class override when providing it in the xaml.
> 
> Want to rule out it's a nullability issue

Thank you very much. 
After I cancel inheriting ReactiveWindow in MainWindow.xaml.cs, VS can successfully compile the project.

Is this issue a bug, or is it designed to work like this?

**Comment by glennawatson** [comment] 2021-11-06 13:12
Not a bug per say. The xaml creates a .cs file in the obj directory. Only one of the partial classes needs the base class declaration and the auto generated file already contains it. 

Anyway glad it's working will close this issue now.

**Closed by glennawatson** 2021-11-06 13:12 UTC
Labels: bug
