### ISSUE TITLE
[BUG] XF RefreshView and ReactiveCommand does not get along on iOS

### ISSUE THREAD

**Issue by 1iveowl** [reactiveui/ReactiveUI#2299] opened 2020-01-05 14:15 UTC
**Describe the bug**
I modified the official Xamarin Forms [RefreshView demo](https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/RefreshViewDemo) ever so slightly, replacing the `ICommand` with a `ReactiveCommand`, and the demo broke. 

Specifically, pull-to-refresh will run once, and then never again. 

I'm not entirely sure what goes on, but it feels like the thread the command is running on returns to the caller as soon as the awaited method `RefreshItemsAsync` reached called, rather than after the method has completed, as would be expected. 

I've used `ReactiveCommand`'s in many instances and never seen this behavior, and believe that there's a bug with either `ReactiveCommand` or `RefreshView`. In the case of the later, maybe, someone here could point me in the direction of a course, and I will happily file a bug with XF.

**Steps To Reproduce**
Please see this repro, with the slight change to the official demo: https://github.com/1iveowl/RxUI.RefreshView.Repro/tree/master/src/RefreshViewDemo

**Expected behavior**
Pull-to-refresh would work more than once. 

**Environment**
- OS:       iOS 13.3
- Version   ReactiveUI 11.1.1
- Device:   iOS Simulator and iPad 10,5"

**Code with modification**
```csharp
public class MainPageViewModel : ReactiveObject, INotifyPropertyChanged
    {
        const int RefreshDuration = 2;
        int itemNumber = 1;
        readonly Random random;
        bool isRefreshing;

        public bool IsRefreshing
        {
            get { return isRefreshing; }
            set
            {
                isRefreshing = value;
                OnPropertyChanged();
            }
        }

        public ObservableCollection<Item> Items { get; private set; }

        
        // Replaced:
        //public ICommand RefreshCommand => new Command(async () => await RefreshItemsAsync());

        // Replacement:
        private ReactiveCommand<Unit, Unit> _refreshCommand;

        public ReactiveCommand<Unit, Unit> RefreshCommand
        {
            get => _refreshCommand;
            set => this.RaiseAndSetIfChanged(ref _refreshCommand, value);
        }


        public MainPageViewModel()
        {
            random = new Random();
            Items = new ObservableCollection<Item>();
            AddItems();

            // Added
            DefineRefreshCommandCommand();
        }

        void AddItems()
        {
            for (int i = 0; i < 50; i++)
            {
                Items.Add(new Item
                {
                    Color = Color.FromRgb(random.Next(0, 255), random.Next(0, 255), random.Next(0, 255)),
                    Name = $"Item {itemNumber++}"
                });
            }
        }


        //Added
        private void DefineRefreshCommandCommand()
        {
            RefreshCommand = ReactiveCommand.CreateFromTask<Unit>(async x =>
            {
                await RefreshItemsAsync();
            });

            RefreshCommand.ThrownExceptions.Subscribe(ex => Debug.WriteLine(ex.Message));
        }

        async Task RefreshItemsAsync()
        {
            IsRefreshing = true;
            await Task.Delay(TimeSpan.FromSeconds(RefreshDuration));
            AddItems();
            IsRefreshing = false;
        }

...
    }
```

**Comment by RLittlesII** [comment] 2020-01-06 18:02
@1iveowl Thank You for reporting this, and providing a reproduction.  I am going to do my best to look at your reproduction this week.

**Comment by RLittlesII** [comment] 2020-01-17 07:32
@1iveowl I was able to get this working in the following sample

https://github.com/RLittlesII/Reactive.Sandbox/tree/master/xamarin/forms/ReactiveUI.2299

**Comment by 1iveowl** [comment] 2020-01-17 10:01
I see. 

Can you explain why I need to do the binding in the code-behind like this: 

```csharp
            RefreshView
                .Events()
                .Refreshing
                .InvokeCommand(this, x => x.ViewModel.RefreshCommand);

            this.OneWayBind(ViewModel, x => x.IsRefreshing, x => x.RefreshView.IsRefreshing);
```

Rather doing it in XAML like this:

```xml
        <RefreshView IsRefreshing="{Binding IsRefreshing, Mode=OneWay}"
                     RefreshColor="Teal"
                     Command="{Binding RefreshCommand}">
            <ScrollView>
                <FlexLayout Direction="Row"
                            Wrap="Wrap"
                            AlignItems="Center"
                            AlignContent="Center"
                            BindableLayout.ItemsSource="{Binding Items}"
                            BindableLayout.ItemTemplate="{StaticResource ColorItemTemplate}" />
            </ScrollView>
        </RefreshView>
```

The latter will still not work, everything else kept the same.

I usually keep my code-behind clean, so to do an exception I really would like to understand why.

**Comment by glennawatson** [comment] 2020-01-17 14:37
The xaml version is failing because you have an input of EventArgs to the ReactiveCommand. If you change that to Unit it should work.

**Comment by 1iveowl** [comment] 2020-01-17 14:47
Thank you @glennawatson 

I just tried this and with the change you propose I can run the Refresh once and never again:

My ViewModel now looks like this:

```csharp
...
public ReactiveCommand<Unit, Unit> RefreshCommand { get; set; }

public MainPageViewModel()
{
    random = new Random();
    Items = new ObservableCollection<Item>();
    AddItems();

    RefreshCommand = ReactiveCommand.CreateFromTask(async _ => await RefreshItemsAsync(), outputScheduler: RxApp.MainThreadScheduler);

    _isRefreshing =
        this.WhenAnyObservable(x => x.RefreshCommand.IsExecuting)
            .StartWith(false)
            .DistinctUntilChanged()
            .ToProperty(this, nameof(IsRefreshing), scheduler: RxApp.MainThreadScheduler);
}
...
```

**Comment by glennawatson** [comment] 2020-01-17 15:01
Is RefreshItemsAsync() firing any exceptions. 

Be aware the output scheduler only handle the output from the command. The task will be run on a non UI thread.

**Comment by RLittlesII** [comment] 2020-01-17 15:02
@1iveowl You don't need to.  I choose to use them.  Seems there might be an issue with the `Command="{Binding RefreshCommand}"`.  If this is working without the XAML bindings and adding the XAML bindings back breaks it, then I would have to figure out why the XF binding engine isn't working with `ReactiveCommand`.

**Comment by 1iveowl** [comment] 2020-01-17 15:05
@glennawatson `RefreshItemsAsync()` is not throwing any exceptions. The code is very simple.

@RLittlesII I agree, it seems to be related to the XAML Binding. Just, not sure what and why is causing this.

**Comment by 1iveowl** [comment] 2020-01-21 16:28
Any news on this? :-)

**Comment by xleon** [comment] 2020-01-21 23:21
Same issue here. I had to use a XF `Command` as a proxy to a ReactiveCommand

**Comment by glennawatson** [comment] 2020-01-21 23:37
there may be some significant refactoring involved so the fix won't be instant but will happen.

**Comment by RLittlesII** [comment] 2020-01-21 23:50
To be clear.  This is not an issue with the Xamarin.Forms RefreshView.  There is a bug tagged to look into the `ReactiveCommand` binding.  And it seems there was a similar one reported earlier.

If the sample provided doesn't resolve the ability to interact with the RefreshView, then we should reopen this issue.  Otherwise we should talk about what issues we are seeing with the `ReactiveCommand` bindings on #2316

**Comment by RLittlesII** [comment] 2020-01-24 00:24
After some additional looking at this and conversations in [slack](https://reactivex.slack.com/archives/C02AJB872/p1579699565092400) I had a quick aside with someone on the XF team.  This may be an issue in the `RefreshView` implementation.  We are looking into it and will have something to report back early next week.

**Comment by winterdouglas** [comment] 2020-02-04 09:24
Just to complement what @RLittlesII said about the refreshview, I did some debugging on the command execution past week and discovered that it's potentially an issue with the way XF does the managing of the `IsEnabled` when the refreshview is refreshing, that makes it to go right away off when it starts executing. I've made a video with a few small changes into the XF refreshview implementation and here the result can be seen.

![refreshview_rxcommand](https://user-images.githubusercontent.com/1329194/73731155-43d51480-4738-11ea-91f6-e44e4d6fa342.gif)

**Comment by glennawatson** [comment] 2020-02-04 12:03
See the linked issue that @PureWeen attached and maybe link your video there also.

**Comment by glennawatson** [comment] 2020-02-04 12:03
This is the bug you want to attach to. 

https://github.com/xamarin/Xamarin.Forms/issues/9326

**Comment by RLittlesII** [comment] 2020-05-12 14:48
This was released in Xamarin.Forms 4.6

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.6/4.6.0#swipeview

**Closed by RLittlesII** 2020-05-12 14:48 UTC
Labels: bug, documentation, xamarin-forms
