### ISSUE TITLE
[BUG] AmbiguousMatchException after rebuilding Xamarin Forms project in Visual Studio for Mac

### ISSUE THREAD

**Issue by leszekrogowski** [reactiveui/ReactiveUI#1975] opened 2019-03-18 16:45 UTC
**Describe the bug**
System.Reflection.AmbiguousMatchException is thrown when you use Fody with ObservableAsPropertyAttribute in Xamarin Forms project. The behaviour can be observed directly after rebuilding the solution (when you start changing the code and then build the code seems to be generated correctly). I believe that the problem started occurring in ReactiveUI 9.10.7 (when Fody was upgraded to ver. 4).
Under IlSpy you can notice that Fody has invalidly generated twice:
`private ObservableAsPropertyHelper<string> $FullName;`

**Steps To Reproduce**
Provide the steps to reproduce the behavior:
1. Clone project: https://github.com/leszekrogowski/ReactiveUIFodyBug.git
2. Rebuild it.
3. Run in emulator or device.
4. See error in MainViewModel, line 9:
```
this.WhenAnyValue(
    x => x.FirstName,
    x => x.LastName,
    (firstName, lastName) => $"{firstName} {lastName}")
    .ToPropertyEx(this, x => x.FullName);
```

**Expected behavior**
Fody should correctly generate the code and exception shouldn't be thrown.

**Screenshots**
<img width="638" alt="Screenshot 2019-03-18 at 17 07 30" src="https://user-images.githubusercontent.com/5956968/54545676-6b957f80-49a2-11e9-9f10-24e5e0e62c9f.png">
<img width="1093" alt="Screenshot 2019-03-18 at 17 42 10" src="https://user-images.githubusercontent.com/5956968/54547028-40605f80-49a5-11e9-826a-e2a2dc0bfbce.png">

**Environment(please complete the following information):**
 - OS: macOS Mojave 10.14.3
 - ReactiveUI 9.11.3 (however, I believe that the lib is broken since 9.10.7)
 - Xamarin Forms 3.6.0.220655
 - Visual Studio for Mac 7.8.3 (build 2)
 - Device: Android Emulator

**Comment by RLittlesII** [comment] 2019-03-20 03:56
@leszekrogowski Thanks for providing a repository with the reproduction.  I plan to look at it this week and see what we can figure out.

**Comment by jorisvergeer** [comment] 2019-03-20 12:05
Also happened to our production build. 
Our build server was configured to create an ad hoc build for iphone. And thereafter rebuild with production profile for iphone without a clean in between.

In the second build, we also had duplicate fields in some of our view models. It looks like the msbuild target does not (always) skip assemblies that are already weaved. Or the weaver does not detect that the assemblies are already weaved.

Evidence:
First build:
![image](https://user-images.githubusercontent.com/1906639/54682959-a9181b00-4b10-11e9-8e3b-8ddcec8f4eb5.png)
Second (re)build:
![image](https://user-images.githubusercontent.com/1906639/54683013-d664c900-4b10-11e9-99cc-e09b1fbf72a6.png)

**Comment by leszekrogowski** [comment] 2019-06-07 11:35
@RLittlesII , any update on this issue?

**Comment by RLittlesII** [comment] 2019-06-08 06:08
@leszekrogowski I have been able to reproduce the issue.  I wasn't able to determine how/why Fody is doing this.

**Comment by leszekrogowski** [comment] 2019-08-07 15:55
The problem seems to be fixed in ver. 9.20.1. Can anyone who experienced the problem confirm that too?

**Comment by glennawatson** [comment] 2019-10-15 11:42
Closing this one since it's been a while since people confirmed it as fixed.

**Closed by glennawatson** 2019-10-15 11:42 UTC
Labels: bug, reactiveui-fody
