### ISSUE TITLE
ToProperty does not work on an object that implements IReactiveObject but is not a ReactiveObject

### ISSUE THREAD

**Issue by kjeremy** [reactiveui/ReactiveUI#1199] opened 2016-11-17 21:01 UTC
I'm been using ReactiveUI 6.5 for a while with MvvmCross by implementing a `ToPropertyMvx` helper that works on `IMvxNotifyPropertyChanged` instead of `ReactiveObject`.  This worked until I upgraded to 7.0 and implemented the `IReactiveObject` interface on my base view model class like so:

```csharp
    public  class ReactiveMvxViewModel : MvxViewModel, IReactiveObject
    {
        public event PropertyChangingEventHandler PropertyChanging;
        void IReactiveObject.RaisePropertyChanging(PropertyChangingEventArgs args)
        {
            PropertyChanging?.Invoke(this, args);
        }
    }
```

which should just work as `MvxViewModel` inherits from `INotifyPropertyChanged`.

Now `WhenAnyValue` + `ToProperty` only execute once initially and never again though the view model is firing `PropertyChanged` notifications.

**Comment by shiftkey** [comment] 2016-11-17 21:55
@kjeremy I'd like to understand the behaviour a bit better before continuing, so here's some questions I have:

 - what platform are you running this RxUI code on?
 - does the same behaviour occur with just a plain `.Subscribe()` instead of `.ToProperty()`?
 - if so, with a `.Subcribe()` attached, do you ever see it complete?

**Comment by kjeremy** [comment] 2016-11-21 14:16
This is on Android and the same thing happens with `Subscribe`.  I will try to get a sample app up this week.

**Comment by kjeremy** [comment] 2016-11-23 20:47
@shiftkey I've added a minimal reproduction to https://github.com/kjeremy/MvvmCrossRxUI7

The project uses MvvmCross and ReactiveUI.  In the main activity there is an input string and a boolean that tells you whether or not the string is non-empty (true) or empty (false).  The value never goes to `false`.

Look at `FirstViewModel.cs`.  If the `Hello` string is empty the `_isValid` `ObservableAsPropertyHelper` never gets updated.

**Comment by kjeremy** [comment] 2016-11-27 17:11
After some more digging around it looks like `RaiseAndSetIfChanged` works because `WhenAnyValue` gets triggered in `ExtensionState.notifyObservable` which is independent from raising the `PropertyChanged` event.

See: https://github.com/reactiveui/ReactiveUI/blob/b418df64918da0c78a378af1b846afbab0f4e5ae/src/ReactiveUI/IReactiveObject.cs#L276

**Comment by kentcb** [comment] 2017-01-17 01:50
Relevant: https://github.com/reactiveui/ReactiveUI/pull/875

**Comment by J-Swift** [comment] 2019-02-02 04:33
Hey everyone, I see activity off and on the past couple years here, but I was wondering if there was any change in terms of it being easier/harder to get the two ViewModel paradigms working together?

I was hoping to mix/match the two great libraries together in an identical way as @kjeremy was above (`MvxViewModel` with `IReactiveObject`). I'm spinning my wheels to understand how to make that happen though. I'm still green in C# and Xamarin so that might be the hangup but I'd love to get some experience to chime in and let me know if its possible or not.

Thanks!

**Comment by glennawatson** [comment] 2019-02-02 05:20
Give me a couple days and I'll come up with a example.

**Comment by J-Swift** [comment] 2019-04-11 18:30
Hey @glennawatson sorry to be a bother, I've got a little more experience under my belt not but still can't quite get the two model playing well together. Were you able to get an example together that I might be able to reference? No worries if not : )

**Comment by AlexanderMelchers** [comment] 2020-11-20 10:37
Though an old issue, I've just run into this as well. My set-up is Xamarin Forms 4.8.0.1687 without any additional frameworks, except for ReactiveUI 12.1.5. That is, the issue is not related to MvvmCross. Rather, I've run into it while implementing a group managed by DynamicData, and specifically with the object-type I'm using to maintain the group:

```
public class ItemGroup : ObservableCollectionExtended<ItemViewModel>, IReactiveObject
{
	private string groupHeader;
	
	public event PropertyChangingEventHandler PropertyChanging;

	public string GroupHeader
	{
		get => groupHeader;
		set => this.RaiseAndSetIfChanged(ref groupHeader, value);
	}

	public ItemGroup(IGroup<ItemViewModel, Guid, int> grouping, IScheduler mainThreadScheduler, IScheduler taskpoolScheduler)
	{

		var items =
			grouping
				.Cache
				.Connect()
				.Publish();

		items
			.Count()
			.Select(count => $"Group with {count} items")
			.ObserveOn(mainThreadScheduler)
			.BindTo(this, model => model.GroupHeader);

		items
			.ObserveOn(mainThreadScheduler)
			.Bind(this)
			.DisposeMany()
			.Subscribe();

		items
			.Connect();
	}

	public void RaisePropertyChanged(PropertyChangedEventArgs args)
		=> OnPropertyChanged(args);

	public void RaisePropertyChanging(PropertyChangingEventArgs args)
		=> PropertyChanging?.Invoke(this, args);
}
```

As you can see, my class implements the `IReactiveObject`-interface - which made me think I could use either `BindTo` in combination with `RaiseAndSetIfChanged`, or simply use an `ObservableAsPropertyHelper` in combination with `ToProperty` to set my `GroupHeader`. The `GroupHeader` is then bound in a Xamarin Forms `ListView`'s `GroupHeaderTemplate`. However, though the group header text is recalculates as the group contents change, the changed text is never reflected on screen.

Moving from `ToProperty` to `BindTo` or even a `Subscribe` didn't change this situation. So, after verifying my header text was being recalculated, my first check was to see whether `GroupHeader` was being properly updated:

```
	public string GroupHeader
	{
		get => groupHeader;
		set
		{
			this.RaiseAndSetIfChanged(ref groupHeader, value);
			var a = groupHeader == value;
		}
	}
```

As it turns out, `a` was always true when I expected it to be. Next I overrid the `ObservableCollectionExtended`'s `OnPropertyChanged(PropertyChangedEventArgs e)`-method to see if it was ever called for the `GroupHeader`-property. It wasn't. So I checked whether `RaisePropertyChanged` was ever called for it, and that wasn't either. So, I changed my property to read

```
public string GroupHeader
{
	get => groupHeader;
	private set
	{
		if (groupHeader == value)
		{
			return;
		}

		groupHeader = value;
		RaisePropertyChanged(new PropertyChangedEventArgs(nameof(GroupHeader)));
	}
}
```

This did work (and is the work-around I'm currently using), which explains quite well why I wasn't seeing updates on the screen. However, it did make me think something might be broken inside ReactiveUI for it not to be able to find the `IReactiveObject.RaisePropertyChanged`-method itself...

**Comment by glennawatson** [comment] 2020-11-20 10:45
A fix for this is incoming next major version.

**Comment by AlexanderMelchers** [comment] 2020-11-20 10:47
Cool! Thanks for the quick response, @glennawatson! Will be looking forward to it 👍

**Comment by DamienDoumer** [comment] 2021-02-17 22:04
Hello, I'm using the latest Reactiveui 13 but the issue is still present. I have the same problem as that stated by @J-Swift above (Trying to mix mvvmcross and IReactiveObject).

**Comment by snalesso** [comment] 2021-11-01 18:26
> A fix for this is incoming next major version.

@glennawatson this issue was never fixed 😥

**Comment by glennawatson** [comment] 2021-11-02 22:20
@ChrisPulman is looking into this one, since we both thought he fixed it.

**Comment by ChrisPulman** [comment] 2021-11-03 00:33
```
public class HomeViewModel : BaseViewModel
    {
        private string _hello = "";

        private readonly ObservableAsPropertyHelper<bool> _isValid;

        public HomeViewModel()
        {
            this.WhenAnyValue(x => x.Hello, str => !string.IsNullOrWhiteSpace(str))
                .ToProperty(this, x => x.IsValid, out _isValid);
        }

        public string Hello
        {
            get => _hello;
            set => this.RaiseAndSetIfChanged(ref _hello, value);
        }

        public bool IsValid => _isValid.Value;
    }

public abstract class BaseViewModel : MvxViewModel, IReactiveObject
    {
        private readonly Lazy<Unit> _propertyChangingEventsSubscribed;
        private readonly Lazy<Unit> _propertyChangedEventsSubscribed;

        public BaseViewModel()
        {
            _propertyChangingEventsSubscribed = new Lazy<Unit>(
                                                        () =>
                                                        {
                                                            this.SubscribePropertyChangingEvents();
                                                            return Unit.Default;
                                                        },
                                                        LazyThreadSafetyMode.PublicationOnly);
            _propertyChangedEventsSubscribed = new Lazy<Unit>(
                                                        () =>
                                                        {
                                                            this.SubscribePropertyChangedEvents();
                                                            return Unit.Default;
                                                        },
                                                        LazyThreadSafetyMode.PublicationOnly);
        }

        /// <inheritdoc/>
        public new event PropertyChangingEventHandler PropertyChanging
        {
            add
            {
                _ = _propertyChangingEventsSubscribed.Value;
                PropertyChangingHandler += value;
            }
            remove => PropertyChangingHandler -= value;
        }

        /// <inheritdoc/>
        public new event PropertyChangedEventHandler PropertyChanged
        {
            add
            {
                _ = _propertyChangedEventsSubscribed.Value;
                PropertyChangedHandler += value;
            }
            remove => PropertyChangedHandler -= value;
        }

        private event PropertyChangingEventHandler PropertyChangingHandler;

        private event PropertyChangedEventHandler PropertyChangedHandler;

        /// <inheritdoc/>
        void IReactiveObject.RaisePropertyChanging(PropertyChangingEventArgs args) =>
            PropertyChangingHandler?.Invoke(this, args);

        /// <inheritdoc/>
        void IReactiveObject.RaisePropertyChanged(PropertyChangedEventArgs args) =>
            PropertyChangedHandler?.Invoke(this, args);
    }

[XamlCompilation(XamlCompilationOptions.Compile)]
    [MvxContentPagePresentation(WrapInNavigationPage = true)]
    public partial class HomePage : MvxContentPage<HomeViewModel>, IViewFor<HomeViewModel>
    {
        public HomePage()
        {
            InitializeComponent();
            this.WhenActivated(d =>
            {
                this.Bind(ViewModel, vm => vm.Hello, v => v.RxUITextTest.Text).DisposeWith(d);
                this.OneWayBind(ViewModel, vm => vm.IsValid, v => v.CbxIsValid.IsChecked).DisposeWith(d);
            });

        }

        protected override void OnAppearing()
        {
            base.OnAppearing();

            if (Application.Current.MainPage is NavigationPage navigationPage)
            {
                navigationPage.BarTextColor = Color.White;
                navigationPage.BarBackgroundColor = (Color)Application.Current.Resources["PrimaryColor"];
            }
        }

        object IViewFor.ViewModel
        {
            get => ViewModel;
            set => ViewModel = (HomeViewModel)value;
        }
    }

<?xml version="1.0" encoding="utf-8" ?>
<views:MvxContentPage x:TypeArguments="viewModels:HomeViewModel"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:views="clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms"
    xmlns:mvx="clr-namespace:MvvmCross.Forms.Bindings;assembly=MvvmCross.Forms"
    xmlns:local="clr-namespace:MvvmXRxUi.UI.Pages"
    x:Class="MvvmXRxUi.UI.Pages.HomePage"
    xmlns:viewModels="clr-namespace:MvvmXRxUi.Core.ViewModels.Home;assembly=MvvmXRxUi.Core"
                      Title="Main page">
    <ContentPage.Content>
        <StackLayout>
            <CheckBox x:Name="CbxIsValid" />
            <Entry x:Name="RxUITextTest" 
                Text="Welcome!!&#10;App scaffolded with MvxScaffolding"
                VerticalOptions="CenterAndExpand" 
                WidthRequest="200"
                HorizontalOptions="CenterAndExpand" />
        </StackLayout>
    </ContentPage.Content>
</views:MvxContentPage>

```
ViewModel, IReactiveObject implimentaion and View demonstrating that ReactiveUI and MvvmCross work with ToProperty and IReactiveObject, The current release does not support ToPropertyEx with IReactiveObject.

If there is something more that I have missed please post a Repo demonstrating the issue

**Closed** 2021-11-03 00:54 UTC
Labels: reactiveui-core, future

**Comment by snalesso** [comment] 2021-11-04 20:20
Probably I'm missing something, this is my sample:

	public class PropertyChangedBase : INotifyPropertyChanged, INotifyPropertyChanging, IReactiveObject
    {
        #region INotifyPropertyChanged

        public virtual event PropertyChangedEventHandler? PropertyChanged;
        public virtual void RaisePropertyChanged([CallerMemberName] string? propertyName = null) => this.RaisePropertyChanged(new PropertyChangedEventArgs(propertyName));

        #endregion

        #region INotifyPropertyChanging

        public event PropertyChangingEventHandler? PropertyChanging;
        public virtual void RaisePropertyChanging([CallerMemberName] string? propertyName = null) => this.RaisePropertyChanging(new PropertyChangingEventArgs(propertyName));

        #endregion

        #region IReactiveObject

        public void RaisePropertyChanged(PropertyChangedEventArgs args) => PropertyChanged?.Invoke(this, args);
        public void RaisePropertyChanging(PropertyChangingEventArgs args) => PropertyChanging?.Invoke(this, args);

        #endregion
    }

    public class MainWindowViewModel : PropertyChangedBase
    {
        public MainWindowViewModel()
        {
            this._hasMessageOAPH = this._messageBheavior
                .Select(x => !string.IsNullOrWhiteSpace(x))
                .Do(x => Debug.WriteLine($"Has Message changed: {x}"))
                .ObserveOn(RxApp.MainThreadScheduler)
                .ToProperty(this, nameof(this.HasMessage));
        }

        private readonly BehaviorSubject<string?> _messageBheavior = new(null);
        public string? Message
        {
            get { return this._messageBheavior.Value; }
            set { this._messageBheavior.OnNext(value); }
        }

        private readonly ObservableAsPropertyHelper<bool> _hasMessageOAPH;
        public bool HasMessage => this._hasMessageOAPH.Value;
    }

    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.DataContext = new MainWindowViewModel();
            this.InitializeComponent();
        }
    }

	<Window x:Class="WpfApp2.MainWindow"
			xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
			xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
			xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
			xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
			d:DataContext="{d:DesignInstance Type=local:MainWindowViewModel, IsDesignTimeCreatable=False}"
			xmlns:local="clr-namespace:WpfApp2"
			mc:Ignorable="d"
			Title="MainWindow" Height="Auto" Width="300">
		<Grid>
			<Grid.RowDefinitions>
				<RowDefinition Height="*" MinHeight="8"/>
				<RowDefinition Height="Auto"/>
				<RowDefinition Height="8"/>
				<RowDefinition Height="Auto"/>
				<RowDefinition Height="8"/>
				<RowDefinition Height="Auto"/>
				<RowDefinition Height="*" MinHeight="8"/>
			</Grid.RowDefinitions>
			<Grid.ColumnDefinitions>
				<ColumnDefinition Width="8"/>
				<ColumnDefinition Width="*"/>
				<ColumnDefinition Width="8"/>
			</Grid.ColumnDefinitions>
			<TextBox Text="{Binding Message, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" Grid.Column="1" Grid.Row="1"></TextBox>
			<TextBlock Text="{Binding Message, Mode=OneWay, UpdateSourceTrigger=PropertyChanged}" Grid.Column="1" Grid.Row="3"></TextBlock>
			<TextBlock Text="{Binding HasMessage, Mode=OneWay, UpdateSourceTrigger=PropertyChanged}" Grid.Column="1" Grid.Row="5"></TextBlock>
		</Grid>
	</Window>

**Comment by snalesso** [comment] 2021-11-04 20:28
I tried this too but still can't get it

    public class MainWindowViewModel : PropertyChangedBase
    {
        public MainWindowViewModel()
        {
            this._hasMessageOAPH = this.WhenAnyValue(x => x.Message)
                .Select(x => !string.IsNullOrWhiteSpace(x))
                .Do(x => Debug.WriteLine($"Has Message changed: {x}"))
                .ToProperty(this, nameof(this.HasMessage));
        }

        private readonly BehaviorSubject<string?> _messageBheavior = new(null);
        private string? _message = null;
        public string? Message
        {
            get { return this._message; }
            set
            {
                this.RaisePropertyChanging();
                this._message = value;
                this.RaisePropertyChanged();
            }
        }

        private readonly ObservableAsPropertyHelper<bool> _hasMessageOAPH;
        public bool HasMessage => this._hasMessageOAPH.Value;
    }

**Comment by snalesso** [comment] 2021-11-04 21:05
@ChrisPulman sample repo: https://github.com/snalesso/IReactiveObjectTest

**Comment by snalesso** [comment] 2021-11-05 17:12
Misinterpreted [this comment](https://github.com/reactiveui/ReactiveUI/issues/1199#issuecomment-958531004) (didn't pay attention and thought it was an MVVM Cross specific solution). Actually it is the universal solution.
Thank you Chris for your time.
