### ISSUE TITLE
[BUG] [XamForms] FileNotFoundException Could not load file or assembly 'ReactiveUI.Winforms' or one of its dependencies when create a new RoutingState upon startup

### ISSUE THREAD

**Issue by BoutemineOualid** [reactiveui/ReactiveUI#2056] opened 2019-05-30 14:05 UTC
**Describe the bug**

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**

- OS:       
- Version   
- Device:   

**Additional context**

**Comment by glennawatson** [comment] 2019-05-30 14:06
Duplicate of https://github.com/reactiveui/ReactiveUI/issues/2049

**Closed by glennawatson** 2019-05-30 14:06 UTC
Labels: bug

**Comment by JigarM** [comment] 2019-06-15 10:53
Hello @glennawatson 
I'm still gettin error as below : 
```
System.IO.FileNotFoundException: Could not load file or assembly 'ReactiveUI.Winforms' or one of its dependencies
  at System.AppDomain.Load (System.Reflection.AssemblyName assemblyRef, System.Security.Policy.Evidence assemblySecurity) [0x00076] in <58604b4522f748968296166e317b04b4>:0
  at System.AppDomain.Load (System.Reflection.AssemblyName assemblyRef) [0x00000] in <58604b4522f748968296166e317b04b4>:0
  at at (wrapper remoting-invoke-with-check) System.AppDomain.Load(System.Reflection.AssemblyName)
  at System.Reflection.Assembly.Load (System.Reflection.AssemblyName assemblyRef) [0x00005] in <58604b4522f748968296166e317b04b4>:0
  at ReactiveUI.Reflection+<>c.<.cctor>b__16_1 (System.Reflection.AssemblyName assemblyName) [0x00035] in <319cc091d4aa4ae1981adebd2ecaaa2a>:0
```
Please look in snap that I attached , is very appreciate if it's resolving

![Screen Shot 2019-06-15 at 4 19 00 PM](https://user-images.githubusercontent.com/2315291/59550567-c7fc4100-8f89-11e9-99e6-05364e4442e2.png)
![Screen Shot 2019-06-15 at 4 18 48 PM](https://user-images.githubusercontent.com/2315291/59550568-cb8fc800-8f89-11e9-9025-61f7feb98af3.png)

**Comment by glennawatson** [comment] 2019-06-15 16:29
It's a handled exception so not a bug. If you can't get past it for some reason feel free to open an issue then
