### ISSUE TITLE
.NET Native compiled build: binding issue with PasswordBox

### ISSUE THREAD

**Issue by tyress** [reactiveui/ReactiveUI#1330] opened 2017-03-31 08:52 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When compiled with .NET Native, binding PasswordBox.Password will only pass an empty string.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Code like so:
`
d(this.Bind(ViewModel, x => x.Password, x => x.password.Password));`

or

`d(this.WhenAnyValue(x => x.password.Password).BindTo(this, x => x.ViewModel.Password)); `

Compile without .NET Native Toolchain: Works with input password
Compile with .NET native Toolchain: Viewmodel receives empty string

**What is the expected behavior?**

Input password is received in ViewModel. This works in any use-case when not compiled with .NET Native tool chain

**What is the motivation / use case for changing the behavior?**

App must be compiled with .NET Native Toolchain to upload to the store

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**

Windows 10 (UAP), SDK build 10.14393, ReactiveUI-Core version was initially 6.5.0 but an upgrade to 7.2.0 did not change the situation. Build is x64 Debug or Release, compiled with .NET Tool chain

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
Only PasswordBox seems to have this problem. All text-related controls seem to be OK. There is a result on the PasswordBox when accessed directly on the UI without Reactive

**Comment by glennawatson** [comment] 2017-03-31 11:29
PasswordBox has a whole heap of different security requirements compared to traditional boxes though I would argue. Because of this the Password property is not a DependencyProperty. Traditionally Microsoft encourages you to use the SecurePassword property which is a SecureString, and only convert it to a unsecured string right before you need to use it. So it has a whole heap of extra requirements compared to your average TextBox.

**Comment by tyress** [comment] 2017-04-03 00:14
Thanks for this comment. A little strange though that while it isn't a Dependencyproperty, I was able to bind to it outside of .NET toolchain mode

**Comment by MattWhilden** [comment] 2017-04-11 00:07
I work on the .NET Native runtime and compiler team. This definitely seems like something we'd like to investigate. As I'm (more or less) completely ignorant of ReactiveUI I'll probably need a bit more detailed info to produce a local repro (if it's really just those lines above an a few nuget references please just tell me I'm being dense). If someone can share a GitHub link to a project that demonstrates the issue that's ideal but an [ilcRepro.zip](https://github.com/dotnet/core/blob/master/Documentation/ilcRepro.md)file will also work. The repro file takes a bit longer for me to dig through but may be less work on your end...

One thing that may help get you unblocked is to see if this issue still reproduces on the latest set of .NET Native tools (v1.6). Here’s some instructions on how to get to latest of everything:
- Install VS 2017 RTM and pick the UWP workflow at install
- Open the project
- Open the nuget package manager
- Select the package for Microsoft.NETCore.UniversalWindowApplication (aka the UWP metapackage)
- Update to 5.3.2 (this will pull down v1.6 of .NET Native)
- Build and see if it repros!

Anyhow, do let me know. I've opened a bug in our internal database about this issue. If it's ever useful, the number is 406415.

**Comment by shiftkey** [comment] 2017-04-11 00:17
> As I'm (more or less) completely ignorant of ReactiveUI I'll probably need a bit more detailed info to produce a local repro (if it's really just those lines above an a few nuget references please just tell me I'm being dense)

@tyress could you put together a quick RxUI demo app to show this problem? This will help escalate things to the right people.

**Comment by MattWhilden** [comment] 2017-04-11 00:35
FWIW, I'm also chasing down another ReactiveUI related issue that may be similar. There's enough info in that report for me to get a local repro set up. That still repros on latest so that makes it marginally less likely that moving to latest will solve this issue.

http://stackoverflow.com/questions/43290601/reactiveui-binding-does-not-work-in-release-build-in-a-uwp-app

**Comment by tyress** [comment] 2017-04-11 05:11
@MattWhilden @shiftkey  I uploaded a very very basic project [here](https://github.com/tyress/reactive_native_passwordbox) (seems easier to just make a GitHub repo than to make a repro file...). Basically a gigantic PasswordBox app that should show both View and ViewModel passwords when .NET Native toolchain is disabled and only the View password when it is enabled. Upgrading to 5.3.2 does not solve the issue.

**Comment by MattWhilden** [comment] 2017-04-11 15:28
Greatly appreciated. I'll take a look today and let you know.

**Comment by MattWhilden** [comment] 2017-04-12 03:35
The good news: These issues appear to be the exact same issue. I've made some progress winding back from ReactiveObject.RaiseandSetIfChanged. The piece of the .NET Native compiler that is responsible for doing reflection analysis is almost certainly getting lost somewhere within various System.Linq.Expressions types and the ReactiveUI layer. When I get to the end of the investigation we should have a pretty good shot at relatively simple workaround.

The bad news: Our various "big hammer" approaches to issues like this aren't effective in this particular case. This means that it'll have to be root caused before I can offer any reasonable workarounds which may take a little while. 

I'll keep at it tomorrow but I have a few other support cases that this investigation is competing with so my progress won't be as swift as I'd prefer. 

@tyress Thanks for posting the workaround in the StackOverflow issue. Hopefully that kind of workaround can keep folks unblocked while my investigation goes on.

**Comment by tyress** [comment] 2017-04-12 15:19
@MattWhilden No problem. Thank you for looking into this.

**Comment by MattWhilden** [comment] 2017-04-14 09:44
So at the end of the day we're not able to properly track which properties on the base XAML controls are going to be necessary for binding at runtime. Unfortunately, if we end up relatively unsure that a property/event/etc of a control isn't going to be used we'll end up stripping it off. When everything is working nicely, this means your app is smaller, your builds are a faster, and you'll be none the wiser. In this case, we end up stripping the controls of their necessary members and ReactiveUI cannot find them at runtime to do the binding. The interaction between the XAML compiler, our analysis engine, and various shared generic delegate instantiations will need to be... uh... harmonized a bit more if we want this to work out of the box. I've added workitems for that to our backlog but any fix is going to be a bit involved so I wouldn't expect it soon.

In the mean time, one way to work around this is to provide the compiler with enough hinting information so that we  don't strip useful things off of the controls you're using. This is done by adding [Runtime Directives](https://msdn.microsoft.com/en-us/library/dn600639%28v=vs.110%29.aspx) into Properties\Default.rd.xml. Some examples below.

Option 1, add just a few controls that seem to be misbehaving:
```
<Type Name="Windows.UI.Xaml.Controls.TextBox" Dynamic="Required All"/>
<Type Name="Windows.UI.Xaml.Controls.Button" Dynamic="Required All"/>
```

Option 2, add all the controls! (warning: this increases app binary size and build times):
```
<Namespace Name="Windows.UI.Xaml.Controls" Dynamic="Required All"/>
<Namespace Name="Windows.UI.Xaml" Dynamic="Required All"/>
```

I hope that helps get folks on their way. Do speak up if it doesn't! Let me know if you have questions/concerns etc. Happy to help.

**Comment by shiftkey** [comment] 2017-04-14 23:16
@MattWhilden this is probably something we can [document](https://github.com/reactiveui/documentation) while we're waiting.

Leaving this open for someone to add a page [here](https://github.com/reactiveui/documentation/tree/master/en/platform-considerations) discussing this scenario and explaining the workaround - unless there's a better spot to put it in the docs.

**Comment by MattWhilden** [comment] 2017-04-15 00:00
A "big hammer" approach would be to have the ReactiveUI nuget package have an rd.xml file with the "Option 2" directives in it. That's sub optimal for a bunch of reasons but could be interesting/useful if the impact of this issue is broader than I currently expect.

**Comment by tyress** [comment] 2017-05-16 05:08
I forgot to mention that Option 1 didn't work for me (Name="Windows.UI.Xaml.Controls.PasswordBox"), I had to put in for the password control, I had to put in <Namespace Name="Windows.UI.Xaml.Controls" Dynamic="Required All"/> as a directive to make it work. Thanks again for your help

**Comment by ooikengsiang** [comment] 2017-07-31 06:03
Encounter the same issue, but on other controls like TextBox, RadioButton and ComboBox.

Option 1 work for TextBox control, but doesn't work correctly for Button, RadioButton and ComboBox.
Option 2 always get an error when compiling. Error:
```
C:\Users\ooiks\.nuget\packages\microsoft.net.native.compiler\1.6.2\tools\Microsoft.NetNative.targets(691,5): error : Internal compiler error: An item with the same key has already been added.
1>  Done executing task "RunILTransforms" -- FAILED. (TaskId:1412)
1>  Done building target "RunILTransforms" in file "ILTransforms" -- FAILED. (TaskId:1412)
1>  Done building project "ILTransforms" -- FAILED. (TaskId:1412)
1>  Compilation failed (TaskId:1412)
1>   (TaskId:1412)
1>  The command exited with code 1201. (TaskId:1412)
1>  Output Property: _IlcExitCode=1201 (TaskId:1412)
1>Done executing task "LoggerBasedExecTask" -- FAILED. (TaskId:1412)
1>Done building target "BuildNativePackage" in project "Bugko.UniversalWindows.csproj" -- FAILED.: (TargetId:148)
```
Anyone have any other idea?

**Comment by tyress** [comment] 2017-07-31 06:11
Can you make sure to check you didn't put the same directive twice @ooikengsiang ? That seems to be what the error is trying to say

**Comment by ooikengsiang** [comment] 2017-07-31 06:59
Yes, I can confirm there aren't any other directive declaration else where.
I'm compiling the project using Visual Studio 2017 (15.3) Preview 6.
There weird part if compile is success if I use Type, but caught such error if I use Namespace.

**Comment by ooikengsiang** [comment] 2017-07-31 07:01
Turn off .NET Native Toolchain do make everything work, but that is the last option I wanted to use.

**Comment by ooikengsiang** [comment] 2017-07-31 13:39
Found a workaround. Primative Type need to be included in order to make them work. For example, if I use CheckBox and bind the IsCheck, I need to include the following line in Default.rd.xml
```
<Type Name="Windows.UI.Xaml.Controls.Primitives.ButtonBase" Dynamic="Required All" />
<Type Name="Windows.UI.Xaml.Controls.Primitives.ToggleButton" Dynamic="Required All" />
<Type Name="Windows.UI.Xaml.Controls.CheckBox" Dynamic="Required All" />
```

If use ComboBox and bind ItemSource and SelectedItem, then the following line is needed in Default.rd.xml
```
<Type Name="Windows.UI.Xaml.Controls.Primitives.Selector" Dynamic="Required All" />
<Type Name="Windows.UI.Xaml.Controls.ComboBox" Dynamic="Required All" />
<Type Name="Windows.UI.Xaml.Controls.ItemsControl" Dynamic="Required All" />
```

My list now look like this in Default.rd.xml
```
<Type Name="Windows.UI.Xaml.Controls.Primitives.ButtonBase" Dynamic="Required All" />
<Type Name="Windows.UI.Xaml.Controls.Primitives.ToggleButton" Dynamic="Required All" />
<Type Name="Windows.UI.Xaml.Controls.Primitives.Selector" Dynamic="Required All" />
    
<Type Name="Windows.UI.Xaml.Controls.TextBox" Dynamic="Required All" />
<Type Name="Windows.UI.Xaml.Controls.Button" Dynamic="Required All" />
<Type Name="Windows.UI.Xaml.Controls.RadioButton" Dynamic="Required All" />
<Type Name="Windows.UI.Xaml.Controls.ToggleSwitch" Dynamic="Required All" />
<Type Name="Windows.UI.Xaml.Controls.CheckBox" Dynamic="Required All" />
<Type Name="Windows.UI.Xaml.Controls.ComboBox" Dynamic="Required All" />
<Type Name="Windows.UI.Xaml.Controls.ItemsControl" Dynamic="Required All" />
```

P.S.: I still can't get the namespace to work, and have no idea why or how.

**Closed** 2017-10-06 15:09 UTC
Labels: universal-windows-platform, waiting-for-response-or-contribution

**Comment by rosd02** [comment] 2019-03-26 18:18
View this to see how to bind it.
https://github.com/reactiveui/ReactiveUI/blob/master/integrationtests/IntegrationTests.WPF/LoginControl.xaml.cs
