### ISSUE TITLE
Binding FallbackValue/TargetNullValue

### ISSUE THREAD

**Issue by bugproof** [reactiveui/ReactiveUI#2527] opened 2020-09-10 14:55 UTC
**Is your feature request related to a problem? Please describe.**

In two-way binding, I want to clear the value of a textbox when SelectedItem of my DataGrid in WPF is null. This is currently very tedious and non-trivial to do with code-behind bindings ReactiveUI recommends using. It is possible with XAML binding though...

**Describe the solution you'd like**

It would be helpful if `Bind` and `OneWayBind` and maybe `BindTo` had an overload to provide fallback value instead of not firing at all see related issue: https://github.com/reactiveui/ReactiveUI/issues/1967

**Describe alternatives you've considered**

These are only workarounds for this missing feature and it gets very messy and tedious when you have more than 1 bindings like that. 

See how bad this looks:
```cs
this.Bind(ViewModel, 
    vm => vm.SelectedUnit.SelectedLayer, 
    v => v.ssccCode.Text, 
    layer => layer?.SsccCode ?? "",
    ssccCode =>
    {
        var layer = ViewModel.SelectedUnit.SelectedLayer;
        if (layer == null) return null;
        layer.SsccCode = ssccCode;
        return layer;
    });
```

There are other solutions but even worse than this.

**Describe suggestions on how to achieve the feature**

Add overloads for `Bind` and other methods for binding that allow you to set fallback values.

**Additional context**

**Comment by worldbeater** [comment] 2020-09-11 14:07
I guess one possible option of resolving this more elegantly would be to introduce a new property at the view model layer named e.g. `SelectedLayerText`, and then add some `WhenAny` and `CombineLatest` calls to synchronize `ViewModel.SelectedUnit.SelectedLayer` with that new `SelectedLayerText` property. No objections about adding support for fallback values though, just suggesting yet another option.

**Comment by bugproof** [comment] 2020-09-11 14:16
@worldbeater yes, that's another workaround which only adds duplicated properties to your code. I'd rather use XAML bindings for cases like this. If you have 10 properties that need such behaviour, you need 10 duplicated properties just for fallback and that's a lot of redundant code which only increases complexity and affects readability.

**Comment by Noggog** [comment] 2020-10-04 23:17
For non two-way-binds, I've set up this experimental API for my own repo:
https://github.com/Noggog/CSharpExt/blob/master/Noggog.WPF/Extensions/RxUIWhenAnyFallbackExperiment.cs

```
this.WhenAnyFallback(x => x.ViewModel.MyNullableProperty!.MyInt, fallback: 42)
    .BindTo(...)
```

Been working like a dream for me, so far.
Perhaps something similar can be set up for two way binding?  Haven't looked at that specific scenario myself, yet

**Closed** 2020-10-04 23:17 UTC
Labels: feature request

**Comment by glennawatson** [comment] 2020-10-04 23:20
This is a duplicate of https://github.com/reactivemarbles/PropertyChanged/issues/77
