### ISSUE TITLE
[BUG] Error CS7069 Reference to type 'MediaElement' claims it is defined in 'Xamarin.Forms.Core', but it could not be found

### ISSUE THREAD

**Issue by DawidBester** [reactiveui/ReactiveUI#2639] opened 2021-01-10 20:46 UTC
**Describe the bug**

After upgrading to Xamarin Forms 5.0.0.1874, my project now fails to compile with the error **CS7069 Reference to type 'MediaElement' claims it is defined in 'Xamarin.Forms.Core', but it could not be found** for ReactiveUI .Events 

This seems to be related to MediaElement changes as described in the [Xamarin Forms 5.0.0.1874 release notes](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/5.0/5.0.0) 

> C# UI, Expander, and MediaElement Moved
> 
> These experimental features have been (or will be soon) migrated to the Xamarin Community Toolkit which everyone should be taking full advantage of. It's a wonderful library of extremely useful Xamarin controls, effects, value converters, and more. In fact, it even has a native CameraView, Avatar view, and RangeSlider control. These features and controls are continuing to grow and improve, and while Xamarin.Forms moves into an extended stable release, we feel it's better for those to ship for now in the tookit. At a future time, they may be brought back into the core library.

Adding the Xamarin Community Toolkit to the project, did not resolve the issue.

**Steps To Reproduce**

Use ReactiveUI Events in code
Upgrade to Xamarin Forms 5.0.0.1874
Code no longer compiles

**Workaround**
Downgrade to Xamarin Forms 4.8.0.1821

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/33708055/104134706-46cc9080-53f0-11eb-9264-3de163203a3d.png)

**Environment**

- OS:       
- Version   
- Device:   

**Additional context**

**Comment by glennawatson** [comment] 2021-01-10 20:54
Consider using pharmacist in your netstandard forms project. It will be a 100% match to your xamarin forms version

**Comment by glennawatson** [comment] 2021-01-10 21:01
The plan is to soonish deprecate the events based projects in favour of pharmacist btw.

**Comment by Px7-941** [comment] 2021-01-15 07:32
Duplicate of #2638

**Comment by josuepmarchena** [comment] 2021-02-02 14:40
+1

**Comment by josuepmarchena** [comment] 2021-02-02 14:41
any idea to resolve it?

**Comment by AlexanderMelchers** [comment] 2021-02-02 14:47
@josuepmarchena, as stated, you can downgrade your version of Forms as a work-around. The other work-around I've found is to stop using the `ReactiveUI.Events.XamForms`-library, as @glennawatson suggests - either by moving to Pharmacist or by simply not using the functionality it provides.

**Comment by AlexanderMelchers** [comment] 2021-02-02 14:49
@glennawatson, the problem with the solution you're proposing, at least for me, is that my project uses a lot of NuGets hosted on a private repo. [This still seems to cause issues](https://github.com/reactiveui/Pharmacist/issues/77).

**Comment by josuepmarchena** [comment] 2021-02-02 14:53
@AlexanderMelchers, Thank you very much, I think, for now, I'm going to downgrade the Xamarin.Forms version

**Closed** 2021-08-17 02:35 UTC
Labels: bug

**Comment by glennawatson** [comment] 2021-08-17 02:37
Use of the [source generators](https://github.com/reactivemarbles/ObservableEvents) or [pharmacist](https://github.com/reactiveui/pharmacist) is recommended if there is a mismatch with xamarin forms and our version. We also have bumped the Xamarin Forms to v5 now.
