### ISSUE TITLE
[BUG] ReactiveUI.Fody NuGet packages cause positive virus scans.

### ISSUE THREAD

**Issue by davidgregan** [reactiveui/ReactiveUI#2765] opened 2021-05-20 18:15 UTC
.NET 5 WPF applications that contain the ReactiveUI.Fody NuGet package trigger antivirus.

**Steps To Reproduce**

1) Open Visual Studio 2019 and create new .NET 5 WPF project.
2) Add the most recent ReactiveUI and ReactiveUI.Fody NuGet packages to the project.
3) Add a property with the [Reactive] attribute to one of the project classes.
3) Compile the project.
4) upload the project's compiled DLL file to VirusTotal to see the positive scans.

**Expected behavior**
For compiled applications using Fody to not be indentified as malicious.

**Screenshots**

![image](https://user-images.githubusercontent.com/3603658/119028728-09ab7880-b965-11eb-871e-8dfd939072b1.png)

**Environment**

- OS:      Windows Server 2016
- Version   
- Device:   Windows Server 2016 VM

**Additional context**

**Comment by dpvreony** [comment] 2021-05-20 23:06
can you provide a link to the report please. not a bug as false positive in the anti virus product

**Comment by davidgregan** [comment] 2021-05-21 17:37
Here is the virustotal report: [https://www.virustotal.com/gui/file/ba5146a407136c67564c82747b6f7ab2dbdb16e0f0fb80e27b303f25e6ea86eb/detection](https://www.virustotal.com/gui/file/ba5146a407136c67564c82747b6f7ab2dbdb16e0f0fb80e27b303f25e6ea86eb/detection)

**Comment by dpvreony** [comment] 2021-05-21 21:45
thanks.

have you tried with a release build? your PE header shows debug symbols are attached? i had an initial look yesterday suggested it could be a false positive on a debug build, or embedded pdb's.

i'm looking at options to put a check into our CI

**Comment by nathanpovo** [comment] 2021-06-18 10:07
I'm also running into this issue.

In my case, the antivirus is flagging the project during development which gets very annoying when files get locked up and can't be removed unless the computer is restarted.

I'm on Windows 10, and using .NET 5.0 (but this also happened on other .NET versions).

**Comment by dpvreony** [comment] 2021-06-19 11:29
which anti virus product?

**Comment by nathanpovo** [comment] 2021-06-21 06:43
> 
> 
> which anti virus product?

Symantec Endpoint Protection.

![image](https://user-images.githubusercontent.com/17831160/122717947-97cc9480-d26c-11eb-8a36-fa22203f5bd3.png)

Clicking the link in the risk column sends you to the URL https://www.broadcom.com/support/security-center?vid=4294779571, which doesn't explain anything.

**Comment by nathanpovo** [comment] 2021-08-03 09:36
I have managed to get symantec to stop spitting out false negatives.

What I ended up doing is

-  signing all of the projects in the solution (I used a random key generated by visual studio and just applied it to all the projects)
-  remove all uses, and references to ReactiveUI.Fody

Both of these steps are required; not doing either one of them caused symantec to still throw false positives.

I assume symantec has some issues with the way ReactiveUI.Fody generates code. Hopefully, when we can use .NET's code generation, symantec won't be so fussy and I can remove all the boilerplate ViewModel property code.

**Comment by glennawatson** [comment] 2021-08-03 09:39
ReactiveUI.Fody does some non-standard names and stuff behind the scenes. I have a rewrite I been planning on getting out for a month or two which fixes up a lot of the outstanding bugs.

.NET Source Generators wouldn't likely work in these scenarios unless there is a partial class.

**Comment by ChrisPulman** [comment] 2024-08-03 01:40
Please try our ReactiveUI.SourceGenerators, I will close this as Fody is no longer in active development

**Closed by ChrisPulman** 2024-08-03 01:40 UTC
Labels: future
