### ISSUE TITLE
Command Binding Exception on Xamarin Forms 3.0

### ISSUE THREAD

**Issue by W2K** [reactiveui/ReactiveUI#1652] opened 2018-05-20 09:39 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using BindCommand like this:
`this.BindCommand(ViewModel, q => q.LoginCommand, q => q.LogIn);`
or like this : 
 ' this.BindCommand(ViewModel, q => q.LoginCommand, q => q.LogIn,nameof(LogIn.Clicked)) ; '
Splat is not able to resolve 
' ReactiveUI.ICommandBinderImplementation, ReactiveUI, Version=8.2.0.0, Culture=neutral, PublicKeyToke… '
giving exception:
' System.IO.FileNotFoundException '
It happens only to Command Binding, other bindings work properly.
I use latest Xamarin Forms 3.x + RxUI 8.2.x (nuget latest, but same happens on 8.0.1)
I also use Autofac as dependency resolver - as implementtation of Splat's IMutableDependencyResolver

The command is defined as 
`loginCommand = ReactiveCommand.CreateFromTask(async _ =>
              {
                  await authenticationWorkflowService.LoginAsync(SelectedTennant, UserName, Password);
              },canLogin,outputScheduler: RxApp.MainThreadScheduler);` 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
As described above

**What is the expected behavior?**
It should be possible to use Command

**What is the motivation / use case for changing the behavior?**
N/A

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Asesjix** [comment] 2018-05-20 10:49
Is this related to #1651?

**Comment by ghuntley** [comment] 2018-05-20 11:32
Can you please create a small project that reproduces the issue? We can do a release pretty fast after verifying/resolution. We need a repro tho.

**Comment by W2K** [comment] 2018-05-21 07:30
I am not able to deliver the example solution (lack of time, to configure it the same way I have on my side).
I looked a bit throught the sources of RecativeUI and I have found a potential problem in this case.

I use Autofac as DI conatiner. In the class CommandBinding.cs:

` Locator.Current.GetService<ICommandBinderImplementation>()`

Seems that it is registered directly in Splat, but since I am using custom IMutableDependencyResolver, it is likely that RxUI does not register it for Autofac to be available. 

It is most likely that it is my fault.

**Comment by ddotlic** [comment] 2018-09-27 12:09
@ghuntley The problem is real and exists for anyone that:

1. Uses something else for dependency resolution (so Splat's `Locator.Current` has been set to custom impl which directs type resolution elsewhere) which **throws** when it can't resolve a type
2. Uses `BindCommand` from the view (IOW, has gone "all the way" ReactiveUI and isn't using bindings in the XAML)

In my case, the combination is Autofac and WPF but as long as above two criteria is filled, the same can be observed.

The problem is that - as is above indicated - the initialization of command bindings in ReactiveUI tries to resolve the `ICommandBindingImplementation` and expects (?!?) potentially `null` so when it does receive `null` it creates a new `CommandBinderImplementation`.

The reason I post is not to nag to you to fix this - though it would be nice - but to offer solution for others who might stumble upon the same problem and find themselves here 😉 

The workaround is simple: simply register an instance of `CommandBinderImplementation` as `ICommandBinderImplementation` using your DI library of choice and everything will work like a charm (not posting exact syntax as it differs from library to library).

Another workaround would be to return `null` when your DI library cannot resolve a dependency (I don't recommend this, but it's an option) inside your override of the `IMutableDependencyResolver`.

Hope this helps someone and FYI: I'm enjoying Reactive UI immensely, thank you!

**Comment by RLittlesII** [comment] 2018-09-27 12:31
@ddotlic Can you provide a sample solution that reproduces the problem?  I am using ReactiveUI and Autofac on Xamarin.Forms and I have not experienced this for out of the box Xamarin controls.  I have had to create my own Command Binders for custom controls, but this sounds like you're having issues with stock controls.

In the case of the custom command binders, I have had to register them against my DI container.

**Comment by ddotlic** [comment] 2018-09-27 12:56
@RLittlesII I am working on a closed source thing so hopefully it'll be easier to explain how to reproduce this than to extract code from my solution.

Yes, this is with default command binders, nothing custom.

The key moment is the implementation of `IMutableDependencyResolver.GetService`.

My implementation is basically this:
```CSharp
return string.IsNullOrEmpty(contract)
                ? _container.Resolve(serviceType)
                : _container.ResolveNamed(contract, serviceType);
```

where `_container` is Autofac `IContainer`.

By default, ReactiveUI does this `Locator.Current.GetService<ICommandBinderImplementation>() ??
new CommandBinderImplementation();` [here](https://github.com/reactiveui/ReactiveUI/blob/a9e3373962c35daf8cea0129ae2b5856f4f0a5e5/src/ReactiveUI/CommandBinding.cs#L27)

By default, no instances of `ICommandBinderImplementation` are registered, so Autofac throws.

I've seen some implementations (at least one Autofac based) of `IMutableDependencyResolver` which catch the exception thrown by the DI library and return `null` but I think that this is anti-pattern (if one does DI it should be done all the way).

Hope this helps.

**Comment by ddotlic** [comment] 2018-09-28 07:18
@RLittlesII Essentially, this boils down to whether you expect your DI to throw when resolving a dependency or to return `null`. It seems that `CommandBinding` implementation of ReactiveUI assumes latter, whereas by default Autofac assumes former. That's why Autofac has `TryResolve` family of (extension) methods (which is rarely used in practice).

A related question is the one about override-ability. I presume that `CommandBinding` does what it does to allow people to override the default `ICommandBinderImplementation`. Having `GetService` throw when a dependency isn't found prevents you from doing so. There are two solutions to this: either add a static method (which actually exists, but is internal `RxApp.EnsureInitialized`) and require people to do their overrides before this method is called or introduce `TryGetService` to Splat. Neither is great, I know.

So strictly speaking this is not a bug in ReactiveUI; it _might_ be considered an issue for Splat or if the documentation clearly states that `GetService` should return `null` when it doesn't find the service, then there's no issue anywhere but in our adapter code. Though I've checked and Splat's docs do not say this way or another 😄 

Personally, I'm fine as things are now. We might want to document things to help others avoid this minor trap.

**Comment by vector-man** [comment] 2018-12-15 04:14
This is also a problem with my project. Thanks for providing a temporary fix!

**Comment by worldbeater** [comment] 2019-03-30 08:12
Now Splat 7.0 released, which has built-in support for `Autofac` in `Splat.Autofac` package. The resolver implementation returns null if any resolution exception occurs https://github.com/reactiveui/splat/blob/master/src/Splat.Autofac/AutofacDependencyResolver.cs Wondering if we should still catch all dependency resolution exceptions on ReactiveUI side or recommend using Splat.Autofac. Thoughts?

**Comment by ddotlic** [comment] 2019-03-30 08:25
I have successfully used my own version of the adapter and I am **not** catching exceptions - why would anyone want that? I _want_ failure if dependencies cannot be satisfied, don’t we all?

IOW it’s nice this is added, but the implementation is IMHO not correct.

**Comment by ddotlic** [comment] 2019-03-30 08:30
Additionally, the bigger problem here is that we are _forced_ to use `Update` - Splat does not respect one of the DI principles which is to build the container once and that’s it. If autofac removes the method (has been obsolete for some time) we won’t be able to update it any more. Not a big deal because it’s already more than feature rich and stable, but still.

**Comment by glennawatson** [comment] 2019-06-13 03:20
This was solved with Splat 7, closing it. Splat is never meant to be a full DI engine just has a locator component. It's focused on speed in it's default functionality.

**Closed by glennawatson** 2019-06-13 03:20 UTC
Labels: bug

**Comment by RalphJacobson** [comment] 2019-07-26 07:25
Just wanted to post a solution for anyone using Splat.Ninject.

Since ICommandBinderImplementation is internal, in order to register an instance of CommandBinderImplementation with Ninject, we need to do the following:

```
using Ninject.Modules;
using ReactiveUI;
using System.Reflection;

namespace Sample
{
  public class SampleModule : NinjectModule
  {
    public override void Load()
    {
      var assembly = Assembly.Load("ReactiveUI.dll");
      var type = assembly.GetType("ReactiveUI.ICommandBinderImplementation");

      Bind(type).To<CommandBinderImplementation>();
    }
  }
}
```
