### ISSUE TITLE
unwind/remove/retire all #if SILVERLIGHT references

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1397] opened 2017-07-14 11:42 UTC
**Do you want to request a *feature* or report a *bug*?**

bug/possible dead code

**What is the current behavior?**

Investigate why `SILVERLIGHT` is still defined in our netstandard branch and 🔥 all references/remove dead code where need be.

```
C:\Dropbox\reactiveui\ReactiveUI>ack SILVERLIGHT
src\ReactiveUI\Platforms\windows-common\AutoDataTemplateBindingHook.cs
41:#if SILVERLIGHT || NETFX_CORE
65:#if !SILVERLIGHT

src\ReactiveUI\Platforms\windows-common\BindingTypeConverters.cs
15:#if !SILVERLIGHT && !NETFX_CORE
41:#if !SILVERLIGHT && !NETFX_CORE

src\ReactiveUI\Platforms\windows-common\PlatformOperations.cs
15:#elif SILVERLIGHT

src\ReactiveUI\ReactiveCollectionMixins.cs
115:#if !SILVERLIGHT
315:#if !SILVERLIGHT
417:#if !SILVERLIGHT

src\ReactiveUI\ReactiveList.cs
765:#if !SILVERLIGHT

src\ReactiveUI\RxApp.cs
203:#if ANDROID || SILVERLIGHT || IOS

src\ReactiveUI.Blend\FollowObservableStateBehavior.cs
15:#if SILVERLIGHT || NETFX_CORE
28:#if SILVERLIGHT || NETFX_CORE
68:#if SILVERLIGHT || NETFX_CORE

src\ReactiveUI.Tests\CommandBindingTests.cs
93:#if !SILVERLIGHT
297:#if !SILVERLIGHT

src\ReactiveUI.Tests\ReactiveCollectionTest.cs
231:#if !SILVERLIGHT
695:#if !SILVERLIGHT
719:#if !SILVERLIGHT
779:#if !SILVERLIGHT
808:#if !SILVERLIGHT
863:#if !SILVERLIGHT
893:#if !SILVERLIGHT
914:#if !SILVERLIGHT
1840:#if SILVERLIGHT
```

**What is the expected behavior?**

We don't support this platform anymore.

**What is the motivation / use case for changing the behavior?**

RIP 

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**

Found on the `develop` branch

**Comment by olevett** [comment] 2017-07-14 13:30
You say "investigate why SILVERLIGHT is still defined" - I'm not convinced it is? Think it should be burnable without much trouble (probably should have done it with the main changes around netstandard, but didn't want to bloat that!)

**Comment by olevett** [comment] 2017-09-05 11:25
This is a duplicate of #1365 I think, not sure which is worth keeping around though, and #1425 should fix both anyways :)

**Comment by ghuntley** [comment] 2017-10-04 13:31
Closing out as duplicate

**Closed** 2017-10-04 13:31 UTC
Labels: up-for-grabs
