### ISSUE TITLE
[BUG] ReactiveCommand not trigger

### ISSUE THREAD

**Issue by zy97** [reactiveui/ReactiveUI#2169] opened 2019-09-17 05:56 UTC
**Describe the bug**

When using ReactiveCommand.CreateFromTask and specifying its outputSchedule as TaskpoolScheduler, it is normal at version 9.22.1, but later, there will be no reaction when triggered once

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**

- OS:   WPF    
- Version   
- Device:   

**Additional context**

**Comment by trucksmart** [comment] 2019-10-10 22:12
I can confirm this isn't working properly unless this is by design.  See the attached project:
[TestReactiveCommandCreateFromTask.zip](https://github.com/reactiveui/ReactiveUI/files/3714823/TestReactiveCommandCreateFromTask.zip)

Clicking randomize only works the first time even though we are observing the changes on the main thread scheduler (ToProperty).

**Comment by trucksmart** [comment] 2019-10-10 23:05
After more investigation the execution fails on these lines:
[ReactiveCommand.cs line 670](https://github.com/reactiveui/ReactiveUI/blob/e3ef2a810047e4ecc205ff862f7de926f457f01b/src/ReactiveUI/ReactiveCommand/ReactiveCommand.cs#L670)
[ReactiveCommandBase.cs line 197](https://github.com/reactiveui/ReactiveUI/blob/e3ef2a810047e4ecc205ff862f7de926f457f01b/src/ReactiveUI/ReactiveCommand/ReactiveCommandBase.cs#L197)

With this error:
> System.InvalidOperationException: 'The calling thread cannot access this object because a different thread owns it.'

The simple fix would be to add `ObserveOn(RxApp.MainThreadScheduler)` before the `OnCanExecuteChanged` subscription but I'm not sure if that's desirable?  What do you think @glennawatson ?

**Comment by glennawatson** [comment] 2019-10-10 23:14
My only concern would be platforms other than WPF which might not care about main thread schedulers.  Seems a reasonable thing though off the top of my head.

Want to do a change and see how the unit tests go?

**Comment by trucksmart** [comment] 2019-10-11 02:34
> 
> 
> My only concern would be platforms other than WPF which might not care about main thread schedulers. Seems a reasonable thing though off the top of my head.
> 
> Want to do a change and see how the unit tests go?

It breaks the tests.  As an example the output of [this test](https://github.com/reactiveui/ReactiveUI/blob/e3ef2a810047e4ecc205ff862f7de926f457f01b/src/ReactiveUI.Tests/Commands/ReactiveCommandTest.cs#L29l) is 3 instead of 2.  I'm going to do some digging.

**Comment by cabauman** [comment] 2020-08-16 11:19
I was looking into this and I confirmed your findings. But may I ask for an example use case someone would want to specify the _output_ scheduler as TaskPoolScheduler? It doesn't make the command execute on said scheduler; it just outputs the results on the scheduler. So it seems like the default RxApp. MainThreadScheduler would suit your needs since you mentioned you're observing on the main thread via ToProperty anyways.

**Comment by ChrisPulman** [comment] 2021-08-06 22:23
#2849 should have fixed this so closing

**Closed by ChrisPulman** 2021-08-06 22:23 UTC
Labels: bug
