### ISSUE TITLE
How would one make ReactiveView?

### ISSUE THREAD

**Issue by Emailrus** [reactiveui/ReactiveUI#852] opened 2015-05-12 12:57 UTC
I've tried to extend Android.views.View so it would implement same interfaces as ReactiveFragment, but was stopped by internal methods of IReactiveObjectExtensions.

Is there any reason why android side lacking the implmenetation of a View? For Cocoa there are ReactiveNSView and ReactiveControl so it is possible to use them.

Thank you

**Comment by kentcb** [comment] 2017-05-27 09:12
Dupe of #837

**Closed by kentcb** 2017-05-27 09:12 UTC
Labels: question, xamarin-android
