### ISSUE TITLE
[BUG] WPF: When property null, binding does not work

### ISSUE THREAD

**Issue by axgdev** [reactiveui/ReactiveUI#1967] opened 2019-03-08 13:45 UTC
**Describe the bug**
I'm using v9.11.3, When a property is null and we use BindTo, the values don't get updated.

**Steps To Reproduce**
1. Create a new WPF project and replace the MainWindow code with this:
```csharp
public partial class MainWindow : Window, IActivatable
{
	private readonly FormViewModel _viewModel = new FormViewModel();

	public MainWindow()
	{
		InitializeComponent();

		this.WhenActivated(disposable =>
		{
			this.WhenAnyValue(x => x._viewModel.FormText)
				.ObserveOn(RxApp.MainThreadScheduler)
				.BindTo(this, x => x.Title)
				.DisposeWith(disposable);
		});

		Task.Run(async () =>
		{
			await Task.Delay(1000);
			_viewModel.FormText = "SomeText";
		});
	}

	public class FormViewModel : ReactiveObject
	{
		private string _formText;
		public string FormText
		{
			get => _formText;
			set => this.RaiseAndSetIfChanged(ref _formText, value);
		}
	}
}
```

2. Execute the app 
3. After 1 second the Window should read "SomeText" however it stays as "MainWindow"

**Expected behavior**
The bindings should not stop working if the property value is null. Please note that I do not know if it should really be like this by default. But the above code works with WinForms without issues. Also note that adding `.Where(x => x != null)` fixes the problem for WPF.

**Environment(please complete the following information):**
 - OS: Windows
 - Version 10
 - Device: Dell laptop

**Additional context**
This would be the code for a WinForms application:
```csharp
public partial class Form1 : Form, IActivatable
{
	private readonly FormViewModel _viewModel = new FormViewModel();

	public Form1()
	{
		InitializeComponent();

		this.WhenActivated(disposable =>
		{
			this.WhenAnyValue(x => x._viewModel.FormText)
				.ObserveOn(RxApp.MainThreadScheduler)
				.BindTo(this, x => x.Text)
				.DisposeWith(disposable);
		});

		Task.Run(async () =>
		{
			await Task.Delay(1000);
			_viewModel.FormText = "SomeText";
		});
	}

	public class FormViewModel : ReactiveObject
	{
		private string _formText;
		public string FormText
		{
			get => _formText;
			set => this.RaiseAndSetIfChanged(ref _formText, value);
		}
	}
}
```

**Comment by worldbeater** [comment] 2019-03-31 22:44
The issue is definitely with WPF rather than with ReactiveUI. If you try to assign the `null` value to the `Window.Title` property anywhere in your code-behind, you get the following exception: `System.ArgumentException: null is not a valid value for property 'Title'`. That's why ReactiveUI bindings stopped working in this particular case — an exception occured and hadn't been handled.

Well, to resolve the issue you need to either use the `.Where(title => title != null)` operator to prevent nulls from being assigned to WPF `Window.Title` property which doesn't support nulls, or the `Catch` operator to catch `System.ArgumentException` (although the former approach is better than the latter). Yet another option is to do `_formText = string.Empty` to ensure the first value emitted by `WhenAny` is not null. 

The default ReactiveUI behavior is to fail fast when an unhandled exception occurs, regular markup bindings behave the same way. If you bind to anything other than `Window.Title`, for example, to a `TextBlock`, then the exception will not occur and ReactiveUI bindings will work as expected — text blocks support nulls. Tested using ReactiveUI v9.12.1 and the following setup:

**MainWindow.xaml**
```xml
<Window x:Class="WpfApp4.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <TextBlock x:Name="ExampleBlock"/>
    </Grid>
</Window>
```

**MainWindow.xaml.cs**
```cs
public partial class MainWindow : Window, IActivatable
{
    public MainWindow()
    {
        InitializeComponent();
        this.WhenActivated(disposable =>
        {
            this.WhenAnyValue(x => x.ViewModel.FormText)
                .ObserveOn(RxApp.MainThreadScheduler)
                // If you use x => x.Title below, bindings will break 
                // because WPF Window title can not be null.
                // If you don't, it'll be working as expected :)
                .BindTo(this, x => x.ExampleBlock.Text) 
                .DisposeWith(disposable);
        });

        Task.Run(async () =>
        {
            await Task.Delay(1000);
            ViewModel.FormText = "SomeText";
        });
    }

    public FormViewModel ViewModel = new FormViewModel();

    public class FormViewModel : ReactiveObject
    {
        private string _formText;
        public string FormText
        {
            get => _formText;
            set => this.RaiseAndSetIfChanged(ref _formText, value);
        }
    }
}
```

**Comment by glennawatson** [comment] 2019-03-31 23:12
Closing issue since I would expect this to be default functionality.

**Closed by glennawatson** 2019-03-31 23:12 UTC
Labels: windows-presentation-foundation
