### ISSUE TITLE
feature: ViewLocator doesn't set views with their ViewModels

### ISSUE THREAD

**Issue by weitzhandler** [reactiveui/ReactiveUI#2132] opened 2019-08-13 17:43 UTC
Hi,

I'm trying to do VM navigation in the VM project using the registered `IViewLocator`, my views are inheriting `ReactivePage`.

When the page is rendered, the fields are all blank and no data is present at all.
Reading the implementation of the [`ReactivePage`](https://reactiveui.net/docs/handbook/view-location/extending-iviewfor#the-implementation), the reason becomes clear, the `DataContext` property of the views is never set with the `ViewModel` property set internally by the RxUI runtime.
Unfortunately, the UWP/WPF/UNO implementation of the `ReactivePage` doesn't implement it the way it is in Xamarin, thus the `ViewModel` and `DataContext` properties are not wired together.

I personally like it the way it is in Xamarin, automated and done for you. I'd want to apply this behavior for the windows `ReactivePage` as well.

**Comment by weitzhandler** [comment] 2019-08-13 18:06
After updating the `ReactivePage` to look like the Xamarin [like this](https://gist.github.com/weitzhandler/690db02c88289adddf0a35e57d7a1e3e), all issues are gone, having the `IScreen` types registered as singleton.

**Comment by RLittlesII** [comment] 2019-08-13 18:09
@weitzhandler There is nothing stopping you from creating your own `ReactivePageBase` that provides this functionality for your projects.  The link you provided for [Extending View Support](https://reactiveui.net/docs/handbook/view-location/extending-iviewfor#the-implementation) was documented for that exact purpose.

I am not familiar enough with WPF binding to know if "making it work like Xamarin.Forms" is a good idea.  This would most likely be a breaking change for current consumers on those platforms.

Also, the concern of providing a fully instantiated view model from the `Locator` is not a normal ReactiveUI paradigm.  Splat does not support constructor injection by design, which is why we provided the Splat DI adapters.  So the concern you are solving may or may not be something that the platform _should_ be responsible for.

**Comment by weitzhandler** [comment] 2019-08-13 18:25
I see.
Anyway when I was referring to "the Xamarin way", I meant this:
https://github.com/reactiveui/ReactiveUI/blob/33e9eda383e7f592e5fc255a509d09680ce4212c/src/ReactiveUI.XamForms/ReactiveContentPage.cs#L49-L58

Yes I can live with having my internal subclass that does that, I'd at least request that I can add a virtual method `OnViewModelChanged` and maybe also `OnDataContextChanged` to cut on the boilerplate code.

**Comment by glennawatson** [comment] 2019-08-13 21:30
I'm going to close this one since there are multiple ways you can set the data context to the view model. You could set a global style based on the data type of the reactiveusercontrol for example potentially. 

Essentially if you set the datacontext you are forcing n allocations per number of views. Dependency objects attempt to save memory by not having any memory associated with each individual views properties until they mutate from default. By adding the datacontext per view your potentially going to increase all the memory usage. Given we are on mobile now allocations can be important. 

Given most of our users only use xaml binding in small amount of locations and default to using reactive binding this seems unnecessary to force these allocations on our users.

**Closed by glennawatson** 2019-08-13 21:30 UTC
Labels: feature request

**Comment by glennawatson** [comment] 2019-08-13 21:33
Where's the doc mention setting the data context btw - we likely should change that

**Comment by glennawatson** [comment] 2019-08-13 21:42
Btw the reason why frameworks like prism tend to set the datacontext because they don't have a default alternative binding mechanisms and use the xaml binding.

**Comment by glennawatson** [comment] 2019-08-14 05:12
Once they work out https://github.com/microsoft/microsoft-ui-xaml/issues/931 you can do something similar to what a lot of WPF developers do:

So potentially a solution for your problem could be
```xml
<Style>
        <Style.TargetType>
            <local:Type Type="{x:Type local:ReactiveUserControl`1}" />
        </Style.TargetType>
        <Style.BasedOn>
        </Style.BasedOn>
        <Setter Property="DataContext" Value="{Bind ViewModel}"/>
</Style>
```

You can then include it in the App.xaml's ResourceDictionary to get the automatic datacontext binding working.

**Comment by weitzhandler** [comment] 2019-08-14 05:31
> Where's the doc mention setting the data context btw - we likely should change that

[here](https://reactiveui.net/docs/handbook/view-location/extending-iviewfor#the-implementation)

> So potentially a solution for your problem could be

Thank you!
