### ISSUE TITLE
ReactiveList incorrect NotifyCollectionChangedEvent behaviour

### ISSUE THREAD

**Issue by Wouterdek** [reactiveui/ReactiveUI#1683] opened 2018-07-06 20:14 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
ReactiveList has a different interpretation of the term 'Reset' (state is unknown vs list is cleared) and that is fine. However, the class provides a CollectionChanged event that produces events where the collection isn't cleared, but a Reset action as defined [here](https://msdn.microsoft.com/en-us/library/system.collections.specialized.notifycollectionchangedaction(v=vs.110).aspx) is in its eventargs.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create a ReactiveList, use its CollectionChanged event as specified in the event documentation on the Microsoft website, use SuppressChangeNotifications() and you will receive a Reset notification where the list isn't cleared.

**What is the expected behavior?**
Either the CollectionChanged event should output events that match the `NotifyCollectionChangedAction` documentation, or a different event type should be used. Either way, there is a documentation mismatch that is making it very easy to introduce bugs.

**What is the motivation / use case for changing the behavior?**
The code does not match the documentation and this makes tracking ReactiveList very error-prone. Either the event should use correctly match the documentation as provided by Microsoft, or a different type should be used to explicitly indicate that the Reset behaviour is different. Non-ReactiveUI classes that use ReactiveList as a INotifyCollectionChanged object will incorrectly interpret its Reset event.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**
Tested on v8.3.1.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by michaelstonis** [comment] 2018-07-06 20:41
@Wouterdek reset for a `ReactiveList` means that enough has changed in the backing list that it has become unreliable and should be re-evaluated. This is outlined in the [docs](https://reactiveui.net/docs/handbook/collections/reactive-list). This should probably be expanded upon though, as by default, a Reset will be fired once 30% of a ReactiveList's contents have been updated ([reference](https://github.com/reactiveui/ReactiveUI/blob/50403240c792d6d870fbe74961d5df297b4a1f2e/src/ReactiveUI/ReactiveList.cs#L144)). This is configurable though, so you could bump up the threshold to whatever made sense for your application.

**Comment by glennawatson** [comment] 2018-07-06 20:58
This is a performance improvement so it works as intended for most of the use cases. There has been a push towards making ReactiveList put into the Legacy namespace and suggestion on using DynamicData instead https://github.com/RolandPheasant/DynamicData and https://github.com/reactiveui/ReactiveUI/issues/1372

Changing the current INotifyCollectionChange behavior would break binding for many users and potentially cause performance issues.

Also going to close this bug.

**Closed by glennawatson** 2018-07-06 20:58 UTC

**Comment by Wouterdek** [comment] 2018-07-07 07:54
@michaelstonis I know that this is how ReactiveList works, and I don't have any problem with the mechanism itself. The problem is that ReactiveList implements `INotifyCollectionChanged`, but its reset behaviour violates the interface contract as specified by Microsoft. If I make a class that implements IEquatable, but in the `Equals(T)` method I return false instead of true when objects are equal, then that would be bad design even if I documented it because it violates the interface contract.

@glennawatson I did not know about DynamicData, but it seems very interesting. Thanks!

**Comment by glennawatson** [comment] 2018-07-07 15:51
You might be better filling a bug with Microsoft.

Their own source code agrees with our interpretation.

https://github.com/dotnet/corefx/blob/master/src/System.ObjectModel/src/System/Collections/Specialized/NotifyCollectionChangedEventArgs.cs

**Comment by glennawatson** [comment] 2018-07-07 15:54
Also the reference source has the same comment: /// <summary> The contents of the collection changed dramatically. </summary>

https://referencesource.microsoft.com/#System/compmod/system/collections/specialized/notifycollectionchangedeventargs.cs,5cce4343d1536ac7,references

**Comment by glennawatson** [comment] 2018-07-07 15:57
Here's their github so you can open an issue with the docs project: https://github.com/dotnet/docs

**Comment by Wouterdek** [comment] 2018-07-09 07:50
Interesting, seems like there is indeed a mismatch between the source and documentation.
I opened an issue:
https://github.com/dotnet/docs/issues/6368
