### ISSUE TITLE
Remove class constraint from IViewFor and Reactive*(contentpage,usercontrol)

### ISSUE THREAD

**Issue by csteeg** [reactiveui/ReactiveUI#1850] opened 2018-12-03 14:55 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
For all TViewModel's, there is a class constraint, not allowing me te use interfaces for my viewmodels. As far as I can see, the only reason to do this is because 'BindingContext as TViewModel is used to assign the ViewModel property on bindingcontext change. This could be done like:
            if (BindingContext is TViewModel vm)
                ViewModel = vm;
            else
                ViewModel = default(TViewModel);

**What is the expected behavior?**
Allow me to use interfaces if I want to

**What is the motivation / use case for changing the behavior?**
I'm working on live c# editing while your app is running, I need to have interfaces to be able to replace viewmodels with the new implementations that are compiled runtime

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**
All

**Comment by glennawatson** [comment] 2018-12-03 15:01
The issue is no binding engine will allow you to use non classes due to structs not really supporting the property changed paradigm. So when we activated analyzers we got a lot of legitimate warnings about this use case.

**Comment by csteeg** [comment] 2018-12-03 15:04
> The issue is no binding engine will allow you to use non classes due to structs not really supporting the property changed paradigm. So when we activated analyzers we got a lot of legitimate warnings about this use case.

Hmm, ok, thanks for explaining. I'll have to figure out somehting else then I guess :)

**Comment by glennawatson** [comment] 2018-12-03 15:06
I'll have a play around regardless to see if I can get interface based binding working. Structs are the use case we are trying to prevent in this scenario not interfaces.

**Comment by csteeg** [comment] 2018-12-03 15:13
That would be great, I'm testing with my own implementations now, but would be nice if I could use the correct interfaces and baseclasses

**Comment by glennawatson** [comment] 2019-01-29 03:57
How to fix this:

Basically these templates are generated in src/ReactiveUI/VariadicTemplates.tt

We use a templating engine called "T4" which is from Microsoft. If using Visual Studio on windows you can right click on the file to generate the template.

The issue is the `where T : class` https://github.com/reactiveui/ReactiveUI/blob/fa639da5d736c9be5347735f5d088ef265dd0483/src/ReactiveUI/VariadicTemplates.tt#L51

We added this because we wanted to prevent users from using struct's in binding (since it makes no sense) but this stopped people from binding with interfaces. 

There are compiler warnings you need to disable most likely when you do this.

At the top of the file add a 
`#pragma warning disable <compiler warning code> // <description>`

**Comment by glennawatson** [comment] 2019-01-30 03:19
@ajpinedam has agreed to take this one on.

**Comment by glennawatson** [comment] 2019-02-02 23:48
Fixed by #1940

**Comment by glennawatson** [comment] 2019-02-02 23:48
Sorry it took so long @csteeg

**Closed by glennawatson** 2019-02-02 23:48 UTC
Labels: feature request

**Comment by csteeg** [comment] 2019-02-04 10:09
Thanks for getting back at this @glennawatson .
However, this is not the constraint I was talking about specifically, though it is needed for it to work completely :) 
I was talking about the class constraint on IViewFor<T>
I now use a custom IViewFor<T> in my project without the class constraint, so I can use tell the views what ViewModel interface it will receive instead of what specific class.
