### ISSUE TITLE
Consider changing Access Modifiers of PropertyChangingEventManager and related items

### ISSUE THREAD

**Issue by michaelstonis** [reactiveui/ReactiveUI#1167] opened 2016-09-26 16:45 UTC
**Do you want to request a _feature_ or report a _bug_?**
**Feature**

**What is the current behavior?**
In the current implementation, classes such as PropertyChangingEventManager and extension methods within IReactiveObjectExtensions are implemented with an _internal_ Access Modifier. These are only available within the scope of the ReactiveUI projects.

**What is the expected behavior?** 
The Access modifier for UI control creation objects and other necessary components is open enough to create new _Reactive{PlatformControl}_ objects without them being part of the ReactiveUI libraries. 

**What is the motivation / use case for changing the behavior?**
There, inevitably, will be new controls that we want to provide reactive powers to. This is especially becoming more prevalent as google pumps new functionality into Android Support libraries. Adding reactive support to UI objects today is not possible to do without forking the project and building a custom implementation. It _should_ be possible for a developer to add this functionality themselves without having to wait for implementations to be provided by the core ReactiveUI libraries. There are (#845, #852) and have been issues opened in the past for just implementing these kinds of features. 

If we can open up the core components just enough to create a ReactiveUI UI object that can implement IReactiveObject, IReactiveNotifyPropertyChanged<T>, IHandleObservableErrors, etc., then developers can implement these themselves.

**Comment by PureWeen** [comment] 2016-09-26 21:12
Yes Please :-)

As fun as it is recompiling ReactiveUI and marking assemblies so they have access to internal stuff

**Comment by kentcb** [comment] 2017-05-27 09:45
Dupe of #837.

**Closed by kentcb** 2017-05-27 09:45 UTC
