### ISSUE TITLE
Unable to use latest nuget package

### ISSUE THREAD

**Issue by ckpearson** [reactiveui/ReactiveUI#860] opened 2015-05-19 17:27 UTC
I've added the latest nuget package to my WPF project (reactiveui 6.5.0), I've attempted to add the `ViewModelViewHost` to the window, and I'm getting the following build errors:

![image](https://cloud.githubusercontent.com/assets/5690115/7709374/8ccd074c-fe54-11e4-8f49-14f49a2b21ab.png)

I think the culprit is the Splat `IEnableLogger` as my attempts to look for that interface using Resharper have failed, is the nuget dependency pulling in an incorrect version?

**Comment by paulcbetts** [comment] 2015-05-19 17:31
Do you have a reference to Splat?

**Comment by kentcb** [comment] 2015-05-19 23:47
Confirmed. For some reason, Splat is at V1 - presumably a problem with the NuSpec?

Anyway, if you `Update-Package Splat` it updates to latest and things work.

**Comment by kentcb** [comment] 2015-05-19 23:49
Yeah, looks like NuSpec is incorrectly allowing Splat V1:

![image](https://cloud.githubusercontent.com/assets/1901832/7716429/3cc001f0-fed1-11e4-9bc2-7b4d44725150.png)

**Comment by jlaanstra** [comment] 2015-07-20 01:03
Fixed with #905.

**Closed by jlaanstra** 2015-07-20 01:03 UTC
Labels: Bug
