### ISSUE TITLE
how to bind Model to ViewModel

### ISSUE THREAD

**Issue by AltEnter** [reactiveui/ReactiveUI#1286] opened 2017-02-22 06:31 UTC
How can I bind Model  to View Model, stackoverflow I can't find any answer about ReactiveUI。I think the model should be able to general, and verify its own state

![image](https://cloud.githubusercontent.com/assets/10600430/23199727/33aa5102-f90b-11e6-8708-05a4e7bc514f.png)

Please help。

**Comment by PureWeen** [comment] 2017-02-22 07:08
In order to use XAML Bindings the BindingContext has to be set. Has the BindingContext been set to the ViewModel?  Whatever is at a level above the Entry try binding that BindingContext to ViewModel.  

This issue in the next release of RxUI
https://github.com/reactiveui/ReactiveUI/pull/1270

will make life easier

**Comment by AltEnter** [comment] 2017-02-22 07:34
@PureWeen 
![image](https://cloud.githubusercontent.com/assets/10600430/23201240/a9cfe628-f913-11e6-8a6a-9219700a98d8.png)

BindingContext already set;

User Model
![image](https://cloud.githubusercontent.com/assets/10600430/23201290/ec6efc4e-f913-11e6-9e36-5c6f7e857c3c.png)

View Model

![image](https://cloud.githubusercontent.com/assets/10600430/23201342/2053943e-f914-11e6-8e33-d4c7d8320a88.png)

Anything i missing ?

I am totaly block

**Comment by PureWeen** [comment] 2017-02-22 07:39
If you override OnBindingContext can you verify if it's actually set?

```
  protected override void OnBindingContextChanged()
        {
            base.OnBindingContextChanged();
        }
```

**Comment by AltEnter** [comment] 2017-02-22 07:54
I can,

Xaml: {binding UserName}
ViewModel:
private string _userName;
        public string UserName
        {
            get => _userName;
            set => this.RaiseAndSetIfChanged(ref _userName, value);
        }
it's work;

{binding User.UserName} does't work.

**Comment by escamoteur** [comment] 2017-02-22 08:01
I guess your are using Xamarin Forms, right. You cannot bind from Xaml if you use RxUI you have to declare your bindings from the Code behind file like this:

```
           this.WhenActivated(d =>
            {
                this.OneWayBind(ViewModel, vm => vm.YourViewModelProperty, v => v.YourControlToBeBound).DisposeWith(d);
            });
```

in your Pages constructor in the xaml.cs file.

This seems as more work at first glance but it's type safe and supported by Intellisense

Further reading:

https://docs.reactiveui.net/en/user-guide/binding/

**Comment by PureWeen** [comment] 2017-02-22 08:05
I don't quite follow what you mean by this

> User Property is always null.

I don't see in your code where you've assigned the User property to anything

**Comment by AltEnter** [comment] 2017-02-22 08:12
@PureWeen
![image](https://cloud.githubusercontent.com/assets/10600430/23202590/9501bed2-f919-11e6-86bf-cc72c999c165.png)

**Comment by AltEnter** [comment] 2017-02-22 08:19
@escamoteur I have set the bindingcontext,so i can binding from xaml,now my problem is:
if i binding like this chain {binding User.UserName} does't work.
{binding UserName} is work well.

forgive me poor english

**Comment by kentcb** [comment] 2017-02-22 08:20
> You cannot bind from Xaml if you use RxUI

This is not accurate. XAML bindings will work as long as your `BindingContext` is set correctly (which is the case). XAML bindings have a number of disadvantages when compared to RxUI bindings, but they still work fine.

> I don't see in your code where you've assigned the User property to anything

I agree with this. Your `LoginViewModel` does not actually set the `User` property to a value. An easy way to verify this is to stick this in your XAML:

```XML
<Label Text="{Binding .}"/>
```

If you see your VM, it's there and your `User` property must not be set.

**Comment by escamoteur** [comment] 2017-02-22 08:22
ok, agreed when using RxUI I just think in RxUI Terms :-)

But as said, you have to create a User instance somewhere and assign it to your property.

**Comment by AltEnter** [comment] 2017-02-22 08:36
@kentcb if i _user=new User() in the viewmodel constructor,the app will crash,please teach me what should i do.

**Comment by escamoteur** [comment] 2017-02-22 08:49
Does your ViewModel derive from ReactiveObject?

**Comment by AltEnter** [comment] 2017-02-22 08:56
@escamoteur yes,include User

**Comment by AltEnter** [comment] 2017-02-22 09:00
@kentcb the reason i choice xaml binding,
![image](https://cloud.githubusercontent.com/assets/10600430/23204120/42ce6910-f920-11e6-9cfa-44ae92588fff.png)
if i want to bind trigger,RxUI's way is too difficult

**Comment by escamoteur** [comment] 2017-02-22 09:06
I agree if you need relative bindings in Xaml it's better to do it there

**Comment by kentcb** [comment] 2017-02-22 09:26
@AltEnter please provide a repro solution, otherwise we're just guessing.

**Comment by AltEnter** [comment] 2017-02-22 10:31
@kentcb https://github.com/AltEnter/BikeSharing/tree/master

**Comment by AltEnter** [comment] 2017-02-22 15:12
I solved this problem.

right!
![image](https://cloud.githubusercontent.com/assets/10600430/23217165/4e115f8e-f953-11e6-957f-81f45d08ae4e.png)

wrong!
![image](https://cloud.githubusercontent.com/assets/10600430/23217320/cbb6309a-f953-11e6-80d4-826c32bc031e.png)

I am thinking if i don't use ReactiveUI binding,How much benefit can I get from ReactiveUI.

**Comment by PureWeen** [comment] 2017-02-22 18:03
Lots

Bindings really only a small part of the package
https://docs.reactiveui.net/en/index.html

And even though it's a small part of the package ... Binding through reactive is overall a lot nicer and more reliable than XAML bindings.

**Comment by kentcb** [comment] 2017-02-22 22:25
@AltEnter I cannot access your repo (404). Also, you haven't solved the problem - you've just changed it to another.

It's impossible to help any further without code, so please see what you can do on that front.

**Comment by AltEnter** [comment] 2017-02-23 02:50
@kentcb You are right，i thought i solved the problem,but it's not.
![image](https://cloud.githubusercontent.com/assets/10600430/23242582/802e1dac-f9b4-11e6-8b5b-75295c23e995.png)

Repo:https://github.com/AltEnter/BikeSharing

ReactiveUI's documentation is not enough on xamarin if I finish this project and will be a good reference for others

**Comment by kentcb** [comment] 2017-02-23 11:47
@AltEnter turn break-on-exception on and you'll see the problem is that this line (in _ValidateableModel.cs_) is evaluating to `null`:

```C#
_validator = Locator.Current.GetService(GetType()) as AbstractValidator<ValidateableModel>;
```

There's a service registered for that type, but it implements `AbstractValidator<User>`, not `AbstractValidator<ValidateableModel>`.

Pro-tip: always be breaking on all exceptions.

**Closed by kentcb** 2017-02-23 11:47 UTC
