### ISSUE TITLE
[BUG] ReactiveCommand's IsExecuting is not set to true if it's executed again after throwing an exception

### ISSUE THREAD

**Issue by n-ski** [reactiveui/ReactiveUI#2894] opened 2021-08-21 15:01 UTC
**Describe the bug**
If a command throws an exception and it gets executed again later, `IsExecuting` will remain `false`.

**Steps To Reproduce**
Basically added 2 lines of code to an existing test.
``` csharp
[Fact]
public async Task CommandIsExecutingTest()
{
    var subj = new Subject<Unit>();
    bool isExecuting = false;
    Exception? fail = null;
    var fixture = ReactiveCommand.CreateFromTask(async () =>
    {
        await subj.Take(1);
        throw new Exception();
    });
    fixture.IsExecuting.Subscribe(x => isExecuting = x);
    fixture.ThrownExceptions.Subscribe(ex => fail = ex);

    Assert.False(isExecuting);
    Assert.Null(fail);

    fixture.Execute().Subscribe();
    Assert.True(isExecuting);
    Assert.Null(fail);

    subj.OnNext(Unit.Default);

    // Wait 1 ms to allow execution to complete
    await Task.Delay(1).ConfigureAwait(false);

    Assert.False(isExecuting);
    Assert.NotNull(fail);

    fixture.Execute().Subscribe();
    Assert.True(isExecuting); // Fails here.
}
```

**Expected behaviour**
`IsExecuting` should be `true` when the command is executing.

**Environment**
- OS: Windows 10, .NET SDK 5.0.206, Runtime 5.0.9
- ReactiveUI Version: 15.1.1

**Comment by ChrisPulman** [comment] 2021-08-22 18:54
We are trying to come up with a resolve for this but the root cause is in the `System.Reactive` code
https://github.com/dotnet/reactive/issues/1256
This issue has been outstanding for quite some time.

**Comment by glennawatson** [comment] 2022-01-14 23:01
Closing this issue due to it being related to the Rx team not RxUI.

**Closed by glennawatson** 2022-01-14 23:01 UTC
Labels: bug, System.Reactive
