### ISSUE TITLE
Error	CS7069	Reference to type 'IEnableLogger' claims it is defined in 'Splat', but it could not be found

### ISSUE THREAD

**Issue by alski** [reactiveui/ReactiveUI#983] opened 2015-11-18 08:02 UTC
Create a new Universal App in VS2015, Nuget Add ReactiveUI 6.5.0 and all is fine. The project compiles and runs

However once you add a call to 
   `this.RaiseAndSetIfChanged(...)`
then you get the compiler error

Severity	Code	Description	Project	File	Line
Error	CS7069	Reference to type 'IEnableLogger' claims it is defined in 'Splat', but it could not be found	Medicine Tracker	c:\...\UseViewModel.cs	22`

Adding a Nuget reference to Splat solves it. I have a feeling this is by design, but for new users could be a roadblock.

**Comment by flagbug** [comment] 2015-11-18 08:33
Probably the same as https://github.com/reactiveui/ReactiveUI/issues/928?

**Comment by alski** [comment] 2015-11-18 20:51
Its similar but not the same, in that RxUI 6.5.0 has no dependency on Splat at all.

**Comment by alski** [comment] 2015-11-18 22:30
Yep, you are right. My mistake.

**Comment by mteper** [comment] 2015-11-19 16:32
The dependency is there according to NuGet, but VS does not bring it in when you add RxUI.

**Comment by shiftkey** [comment] 2015-11-19 21:43
@alski what version of NuGet do you have installed in VS2015?

**Comment by alski** [comment] 2015-12-11 18:29
Sorry for not responding, and worse I've updated NuGet since I raised this. Let me try rolling back the commits and re-trying.

**Comment by ghuntley** [comment] 2015-12-14 22:45
Confirmed - splat is not being brought in automatically when doing a ```Install-Package ReactiveUI``` on a brand new PCL (targeting 259). Installing splat then installing reactiveui however works.

	PM> Install-Package reactiveui
	Attempting to gather dependencies information for package 'reactiveui.6.5.0' with respect to project 'HelloWorldApp.Core', targeting '.NETPortable,Version=v4.5,Profile=Profile259'
	Attempting to resolve dependencies for package 'reactiveui.6.5.0' with DependencyBehavior 'Lowest'
	Resolving actions to install package 'reactiveui.6.5.0'
	Resolved actions to install package 'reactiveui.6.5.0'
	Adding package 'Rx-Interfaces.2.2.5' to folder 'c:\code\HelloWorld\src\packages'
	Added package 'Rx-Interfaces.2.2.5' to folder 'c:\code\HelloWorld\src\packages'
	Added package 'Rx-Interfaces.2.2.5' to 'packages.config'
	Successfully installed 'Rx-Interfaces 2.2.5' to HelloWorldApp.Core
	Adding package 'Rx-Core.2.2.5' to folder 'c:\code\HelloWorld\src\packages'
	Added package 'Rx-Core.2.2.5' to folder 'c:\code\HelloWorld\src\packages'
	Added package 'Rx-Core.2.2.5' to 'packages.config'
	Successfully installed 'Rx-Core 2.2.5' to HelloWorldApp.Core
	Adding package 'Rx-Linq.2.2.5' to folder 'c:\code\HelloWorld\src\packages'
	Added package 'Rx-Linq.2.2.5' to folder 'c:\code\HelloWorld\src\packages'
	Added package 'Rx-Linq.2.2.5' to 'packages.config'
	Successfully installed 'Rx-Linq 2.2.5' to HelloWorldApp.Core
	Adding package 'Rx-PlatformServices.2.2.5' to folder 'c:\code\HelloWorld\src\packages'
	Added package 'Rx-PlatformServices.2.2.5' to folder 'c:\code\HelloWorld\src\packages'
	Added package 'Rx-PlatformServices.2.2.5' to 'packages.config'
	Successfully installed 'Rx-PlatformServices 2.2.5' to HelloWorldApp.Core
	Adding package 'Rx-Main.2.2.5', which only has dependencies, to project 'HelloWorldApp.Core'.
	Adding package 'Rx-Main.2.2.5' to folder 'c:\code\HelloWorld\src\packages'
	Added package 'Rx-Main.2.2.5' to folder 'c:\code\HelloWorld\src\packages'
	Added package 'Rx-Main.2.2.5' to 'packages.config'
	Successfully installed 'Rx-Main 2.2.5' to HelloWorldApp.Core
	Install failed. Rolling back...
	Package 'Splat.1.0.0 : ' does not exist in project 'HelloWorldApp.Core'
	Removed package 'Rx-Main.2.2.5 : Rx-Core [2.2.5, ), Rx-Interfaces [2.2.5, ), Rx-Linq [2.2.5, ), Rx-PlatformServices [2.2.5, )' from 'packages.config'
	Removed package 'Rx-PlatformServices.2.2.5 : Rx-Core [2.2.5, ), Rx-Interfaces [2.2.5, )' from 'packages.config'
	Removed package 'Rx-Linq.2.2.5 : Rx-Core [2.2.5, ), Rx-Interfaces [2.2.5, )' from 'packages.config'
	Removed package 'Rx-Core.2.2.5 : Rx-Interfaces [2.2.5, )' from 'packages.config'
	Removed package 'Rx-Interfaces.2.2.5 : ' from 'packages.config'
	Package 'Splat.1.0.0 : ' does not exist in folder 'c:\code\HelloWorld\src\packages'
	Removing package 'Rx-Main.2.2.5 : Rx-Core [2.2.5, ), Rx-Interfaces [2.2.5, ), Rx-Linq [2.2.5, ), Rx-PlatformServices [2.2.5, )' from folder 'c:\code\HelloWorld\src\packages'
	Removed package 'Rx-Main.2.2.5 : Rx-Core [2.2.5, ), Rx-Interfaces [2.2.5, ), Rx-Linq [2.2.5, ), Rx-PlatformServices [2.2.5, )' from folder 'c:\code\HelloWorld\src\packages'
	Removing package 'Rx-PlatformServices.2.2.5 : Rx-Core [2.2.5, ), Rx-Interfaces [2.2.5, )' from folder 'c:\code\HelloWorld\src\packages'
	Removed package 'Rx-PlatformServices.2.2.5 : Rx-Core [2.2.5, ), Rx-Interfaces [2.2.5, )' from folder 'c:\code\HelloWorld\src\packages'
	Removing package 'Rx-Linq.2.2.5 : Rx-Core [2.2.5, ), Rx-Interfaces [2.2.5, )' from folder 'c:\code\HelloWorld\src\packages'
	Removed package 'Rx-Linq.2.2.5 : Rx-Core [2.2.5, ), Rx-Interfaces [2.2.5, )' from folder 'c:\code\HelloWorld\src\packages'
	Removing package 'Rx-Core.2.2.5 : Rx-Interfaces [2.2.5, )' from folder 'c:\code\HelloWorld\src\packages'
	Removed package 'Rx-Core.2.2.5 : Rx-Interfaces [2.2.5, )' from folder 'c:\code\HelloWorld\src\packages'
	Removing package 'Rx-Interfaces.2.2.5 : ' from folder 'c:\code\HelloWorld\src\packages'
	Removed package 'Rx-Interfaces.2.2.5 : ' from folder 'c:\code\HelloWorld\src\packages'
	Install-Package : Could not install package 'Splat 1.0.0'. You are trying to install this package into a project that 
	targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or 
	content files that are compatible with that framework. For more information, contact the package author.
	At line:1 char:1
	+ Install-Package reactiveui
	+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
	    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
	    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageComma 
	   nd

**Comment by olevett** [comment] 2016-01-06 20:13
I think this has been fixed by #889, but hasn't been released yet
- the main issue is because it's successfully getting Splat 1.0.0, the 1.0.0 NuGet package is compatible with Windows 10/UWP
- the second not getting Splat at all issue is that 1.0.0 doesn't seem to support Profile259.

Before the next release, I think the following should work as another work around (other than installing Splat first)
```powershell
Install-Package ReactiveUI -DependencyVersion Highest
```
forces NuGet to get Splat 1.6.2 which then works correctly.

**Comment by alski** [comment] 2016-06-10 08:50
Bizarrely I've just had this issue again, but this time for a .Net 4.5.2 WPF application from VS2015.
With a single WPF application project, I created a quick UI and then added Reactiveui which came in as 6.5.0, upon adding `myReactiveCommandObject.Subscribe(________)` I got the red wiggles with Reference to type 'IEnableLogger' claims it is defined in 'Splat', but it could not be found

Furthermore, I can resolve this by running `Install-Package Splat -DependencyVersion Highest` which migrated Splat from 1.0.0 to 1.6.2
`Package Manager Console Host Version 3.4.2.830

Type 'get-help NuGet' to see all available NuGet commands.

PM> Install-Package ReactiveUI -DependencyVersion Highest
Package 'ReactiveUI.6.5.0' already exists in project 'Hilt'
PM> Install-Package Splat -DependencyVersion Highest
Attempting to gather dependency information for package 'Splat.1.6.2' with respect to project 'Hilt', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'Splat.1.6.2' with DependencyBehavior 'Highest'
Resolving actions to install package 'Splat.1.6.2'
Resolved actions to install package 'Splat.1.6.2'
Removed package 'Splat.1.0.0' from 'packages.config'
Successfully uninstalled 'Splat.1.0.0' from Hilt
  GET https://www.nuget.org/api/v2/package/Splat/1.6.2
  OK https://www.nuget.org/api/v2/package/Splat/1.6.2 2343ms
Installing Splat 1.6.2.
Adding package 'Splat.1.6.2' to folder 'C:\Dev\Hilt\packages'
Added package 'Splat.1.6.2' to folder 'C:\Dev\Hilt\packages'
Added package 'Splat.1.6.2' to 'packages.config'
Successfully installed 'Splat 1.6.2' to Hilt
Removing package 'Splat.1.0.0' from folder 'C:\Dev\Hilt\packages'
Removed package 'Splat.1.0.0' from folder 'C:\Dev\Hilt\packages'
PM> `

**Comment by ghuntley** [comment] 2016-08-17 08:26
Howdy we have pushed v6.5.1 to NuGet which resolves installation into portable class libraries that target Profile259. This release contains the exact same binaries as v6.5.0 but resolves a nuspec metadata version definition which was causing this problem.

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">.<a href="https://twitter.com/ReactiveXUI">@ReactiveXUI</a> v6.5.1 has been released. Resolves install into Profile259 ie UWP/XamForms. Same binaries as v6.5.0. <a href="https://t.co/gBjxHQxsjZ">pic.twitter.com/gBjxHQxsjZ</a></p>&mdash; Geoffrey Huntley (@GeoffreyHuntley) <a href="https://twitter.com/GeoffreyHuntley/status/765822657463857152">August 17, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Closed by ghuntley** 2016-08-17 08:26 UTC
Labels: bug, rxui, up-for-grabs
