### ISSUE TITLE
[BUG] ReactiveCommand throws exception in UWP app when activated through sharing

### ISSUE THREAD

**Issue by harvinders** [reactiveui/ReactiveUI#2034] opened 2019-05-16 12:34 UTC
**Describe the bug**
In a UWP app, if the app is activated through [receive data api](https://docs.microsoft.com/en-us/windows/uwp/app-to-app/receive-data) the ReactiveCommand invocation raises exception 

**Steps To Reproduce**
I am providing a bare minimum app that reproduces this problem. 
[ReactiveUITestApp1 code](https://github.com/harvinders/ReactiveUITestApp1)

1. Start the Debugging the app in visual studio
2. Using firefox or edge browser, click on the share menu
3. Select ReactiveUITestApp1 from the list of apps
4. From the new application window, click the `Complete` button
5. After the command's `Action` is executed an exception is thrown
 
**Expected behavior**
There should not be an exception or there should be a way to safely invoke the command

**Environment**

- OS:       Windows 10
- Version   1903 

**Additional context**
The project target was set to 1903 with min target of 1809. The ReactiveUI package 9.15.1 was used.

If I remove the command creation in MainViewModel in the main UI of the app, I do not get the exception.

Others have faced similar exception whilst sharing/receiving in UWP, here are some links to provide some pointers why it might be happening

https://stackoverflow.com/a/18643977/1139856
https://github.com/luberda-molinet/FFImageLoading/issues/166

Exception Stacktrace

  | Name | Value | Type
-- | -- | -- | --
▶ | Exception | {System.Exception: A COM call to an ASTA was blocked because the call chain originated in or passed through another ASTA. This call pattern is deadlock-prone and disallowed by apartment call control.  A COM call (IID: {C50898F6-C536-5F47-8583-8B2C2438A13B}, method index: 3) to an ASTA (thread 12132) was blocked because the call chain originated in or passed through another ASTA (thread 22768). This call pattern is deadlock-prone and disallowed by apartment call control.    at System.Runtime.InteropServices.WindowsRuntime.ICommandAdapterHelpers.<>c__DisplayClass1_0.<CreateWrapperHandler>b__0(Object sender, EventArgs e)    at ReactiveUI.ReactiveCommandBase`2.OnCanExecuteChanged() in D:\a\1\s\src\ReactiveUI\ReactiveCommand\ReactiveCommandBase.cs:line 195    at ReactiveUI.ReactiveCommand`2.<.ctor>b__9_6(Boolean _) in D:\a\1\s\src\ReactiveUI\ReactiveCommand\ReactiveCommand.cs:line 671    at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 45    at System.Reactive.Linq.ObservableImpl.RefCount`1._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\RefCount.cs:line 65    at System.Reactive.Subjects.FastImmediateObserver`1.EnsureActive(Int32 count) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\ReplaySubject.cs:line 850    at System.Reactive.Subjects.FastImmediateObserver`1.EnsureActive() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\ReplaySubject.cs:line 752    at System.Reactive.Subjects.ReplaySubject`1.ReplayBase.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\ReplaySubject.cs:line 271    at System.Reactive.Subjects.ReplaySubject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\ReplaySubject.cs:line 167    at System.Reactive.Linq.ObservableImpl.AsObservable`1._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\AsObservable.cs:line 31    at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\DistinctUntilChanged.cs:line 77    at System.Reactive.Linq.ObservableImpl.CombineLatest`3._.SecondObserver.OnNext(TSecond value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\CombineLatest.cs:line 180    at System.Reactive.Linq.ObservableImpl.RefCount`1._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\RefCount.cs:line 65    at System.Reactive.Subjects.FastImmediateObserver`1.EnsureActive(Int32 count) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\ReplaySubject.cs:line 850    at System.Reactive.Subjects.FastImmediateObserver`1.EnsureActive() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\ReplaySubject.cs:line 752    at System.Reactive.Subjects.ReplaySubject`1.ReplayBase.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\ReplaySubject.cs:line 271    at System.Reactive.Subjects.ReplaySubject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\ReplaySubject.cs:line 167    at System.Reactive.Linq.ObservableImpl.AsObservable`1._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\AsObservable.cs:line 31    at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\DistinctUntilChanged.cs:line 77    at System.Reactive.Linq.ObservableImpl.Concat`1._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Concat.cs:line 33    at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 48    at System.Reactive.Linq.ObservableImpl.Scan`2._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Scan.cs:line 49    at System.Reactive.SafeObserver`1.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\SafeObserver.cs:line 40    at System.Reactive.ScheduledObserver`1.Run(Object state, Action`1 recurse) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ScheduledObserver.cs:line 254    at System.Reactive.Concurrency.Scheduler.<>c__DisplayClass49_0`1.<InvokeRec1>b__0(TState state1) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Recursive.cs:line 55    at System.Reactive.Concurrency.Scheduler.InvokeRec1[TState](IScheduler scheduler, Pair`2 pair) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Recursive.cs:line 55    at System.Reactive.Concurrency.CoreDispatcherScheduler.<>c__DisplayClass10_0`1.<Schedule>b__0() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Platforms\UWP\Concurrency\CoreDispatcherScheduler.cs:line 99 --- End of stack trace from previous location where exception was thrown ---    at System.Reactive.Concurrency.CoreDispatcherScheduler.<>c__DisplayClass10_2`1.<Schedule>b__1(Object o, Object e) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Platforms\UWP\Concurrency\CoreDispatcherScheduler.cs:line 119} | System.Exception

**Comment by glennawatson** [comment] 2019-05-16 12:38
Hmm interesting one. We are a bit backlogged on bugs at the moment so hopefully can get a fix in soon. Happy to take a PR if you're able to earlier too

**Comment by hinterlandsupplyco** [comment] 2019-06-21 20:11
@glennawatson @harvinders 

Here is some more reading on the subject: http://www.dansuleski.com/raising-events-across-windows/

We are seeing this bug as well (and posted about it on the reactiveui slack channel a couple days ago). It is caused by the fact that on UWP each new window gets its own ui thread and the way `WaitForDispatcherScheduler` (which is the default scheduler for `RxApp.MainThreadScheduler`) works it is inherently only going to work on a single window app. As @anaisbetts put it in Slack, UWP UI thread situation is a "tire fire" and to quote "ReactiveUI is not designed to handle multiple window apps" - which essentially means no `ProjectionManager`, no `ShareTarget`, no `ApplicationViewSwitcher`, nothing multi-window. While I agree with the first part (and begrudgingly the second part), I am not so sure that RxUI shouldn't be considering these issues.

Anyways. Back to the issue. 

This specific exception is caused by work continuing from one ui thread to another and back. Each one of these windows runs its own dispatcher thread and is an “Application Single Threaded Apartment” (ASTA). Essentially the framework is blocking what it thinks is a potential deadlock. This particular exception is thrown when code running under one STA (1) calls out to another STA (2) and that STA (2) might have to re-enter STA (1) in order to do its work. The framework throws that exception at this point to try and stop you getting into a mess with deadlocks.

I am currently testing a scheduler that can handle multiple windows/dispatchers and will hopefully manage this as well, but we are still testing it and I'm not sure if I'll be able to block this exception yet (which would make my new scheduler useless... 👎).

**Comment by hinterlandsupplyco** [comment] 2019-06-21 21:06
It looks like the exception is thrown because `ICommand` marshals back to the a COM object for event handling... [.NET Reference Source](https://referencesource.microsoft.com/#System/compmod/system/collections/specialized/marshalinghelpers.cs,372)

**Comment by hinterlandsupplyco** [comment] 2019-06-24 13:28
Bounty Added: [BountySource](https://www.bountysource.com/issues/74238746-bug-reactivecommand-throws-exception-in-uwp-app-when-activated-through-sharing)

**Comment by glennawatson** [comment] 2019-06-24 13:32
Any funding requests should go through the open collective. Given we vetted this source of revenue we know it's safe for the rxui organisation to recommend to potential community members to target.

**Comment by glennawatson** [comment] 2019-06-24 13:44
I'll look at your issue free of charge tomorrow for you.

**Comment by hinterlandsupplyco** [comment] 2019-06-24 13:44
> Any funding requests should go through the open collective. Given we vetted this source of revenue we know it's safe for the rxui organisation to recommend to potential community members to target.

Done! 🙌

**Comment by glennawatson** [comment] 2019-06-27 04:13
I was able to get past this problem personally by changing

```cs
            CompleteCommand = ReactiveCommand.Create(() => { }, outputScheduler: CoreDispatcherScheduler.Current);
```

**Comment by glennawatson** [comment] 2019-06-27 04:16
I might make a new issue about the RxApp having a singular access point and support multiple windowing technologies, and close this one since you can use the dispatcher scheduler to correctly. I don't think it's a workaround per say since it's a threading requirement for this problem.

**Closed by glennawatson** 2019-06-27 04:16 UTC
Labels: bug
