### ISSUE TITLE
[BUG] Version 14.1.1 WhenAny.. now returns observable to a nullable regardless of parameter type

### ISSUE THREAD

**Issue by kgday** [reactiveui/ReactiveUI#2812] opened 2021-06-28 07:09 UTC
**Describe the bug**
As a result of upgrading to version 14.1.1 with nullable references enabled in a .net 5.0 wpf project, regardless of the input type,
whenAny.. now returns a nullable reference type.  This means regardless of the input parameters, we have to use WhereNotNull() everywhere or bangs (I reserve them for last resort).  I believe this change came through in issue 2760

**Expected behavior**
The return type should reflect the input value types.

**Comment by glennawatson** [comment] 2021-06-28 07:11
Pending fix https://github.com/reactiveui/ReactiveUI/pull/2808

**Comment by csmager** [comment] 2021-08-05 08:41
I've updated to 14.2.1, which I believe contains the fix for this in #2809. I now have the opposite problem. The signature for e.g. `WhenAnyValue` is now this:

```
public static IObservable<TRet> WhenAnyValue<TSender, TRet>(
    this TSender? sender,
    Expression<Func<TSender, TRet?>> property1)
```
Meaning I can *select* a nullable property, and thus the value could be `null`. But as the return type is not nullable, all the tooling claims it can't be `null` and I don't have to check for it.

**Comment by ChrisPulman** [comment] 2021-08-05 13:22
Thanks for explaining your findings, I will check this functionality, it should allow you to select a nullable parameter/property from the sender and return a stream of values while the parameter/property is not a null value. The TRet? in the expression allows you to select a nullable property without any further markup.

Out of interest are you expecting to receive null values when it is null?

**Comment by csmager** [comment] 2021-08-05 13:31
> The TRet? in the expression allows you to select a nullable property without any further markup.

It lets you select a nullable property, but then it claims to return a stream of non-nullable values. This isn't the case, however. It will return `null` if that property value is `null`.

> Out of interest are you expecting to receive null values when it is null?

Yes, as that's how it has always behaved (as far as I'm aware). For example, when observing a `SelectedItem` property, `null` (nothing is selected) is of interest.

**Comment by ChrisPulman** [comment] 2021-08-05 18:39
I have run a few tests and the key differences between V13 and V14.1 was that a nullable parameter could be selected without further nullable notation and the result was always nullable too, V14.2 does the same but returns a non nullable value type instead but can still return null. 
The exception to this in all cases is for value types where you must check your result has a value and use `x.Value` in a `Select` for example `.Where(x => x.HasValue).Select(x => x!.Value)` or assign to a nullable result without this.

If you are able to provide a sample that demonstrates your issue it would be very helpful in understanding and resolving this if required.

**Comment by kgday** [comment] 2021-08-06 01:24
An example of what I have encountered:
`      
private ObservableAsPropertyHelper<string?> _orwnerName;

//In Constructor:
//the below gets warnings of nullability mismatches - but it shouldn't
_name = this.WhenAnyValue(x=>x.Owner)
  .WhereNotNull()
  .Select(owner => owner.WhenAnyValue(x=>x.Name) // owner.Name is string? (nullable<string>)
  .Switch()
  .ToProperty(this, x=>x.Name);


public string? OwnerName => _ownerName.Value;

`

**Comment by ChrisPulman** [comment] 2021-08-06 06:33
Thanks very much for your patience and assistance.
The issue is with ToProperty rather than with WhenAny / WhenAnyValue. 
Unfortunately none of the existing tests flag this issue and it has gone unseen.

We will update this and add additional tests into ReactiveUI to ensure that this combination always has the desired result.
V13
![image](https://user-images.githubusercontent.com/4910015/128461448-3d554592-7fa9-4697-ad78-d96756755a33.png)
both have compiler issue without using .WhereNotNull
![image](https://user-images.githubusercontent.com/4910015/128461785-8cc191e9-3ce8-4466-b021-dfdbcc1c9074.png)
![image](https://user-images.githubusercontent.com/4910015/128461879-3c28f0b8-0e7e-4460-b3b6-6b8d47ee094e.png)

V14.1.1
![image](https://user-images.githubusercontent.com/4910015/128461999-b7c08595-43ff-4ef1-9712-1beae225f0d8.png)
possible runtime issue as Owner may be null
![image](https://user-images.githubusercontent.com/4910015/128462118-10a24ab7-fc57-43d4-a0f1-ae6183fc1290.png)
compiler issue
![image](https://user-images.githubusercontent.com/4910015/128462225-a0904d6a-0302-4449-a3cc-8b54da7896d2.png)

V14.2.1
![image](https://user-images.githubusercontent.com/4910015/128462383-369c9bbd-4844-4686-bcb5-ed4d5a9e12c3.png)
![image](https://user-images.githubusercontent.com/4910015/128462460-cf76c401-0a10-4a6e-96c8-897cb8506e32.png)
the only option that works with this code (opposite of V13)
![image](https://user-images.githubusercontent.com/4910015/128462518-b04317b9-53fc-4f55-9d78-b86b272f413e.png)

V14.x.x - proposed works with all three scenario's 
![image](https://user-images.githubusercontent.com/4910015/128462627-d293e77e-4606-423c-ac17-31de15afb936.png)
![image](https://user-images.githubusercontent.com/4910015/128462733-8076e548-0979-42a6-befa-070a6c5462ac.png)
![image](https://user-images.githubusercontent.com/4910015/128462796-1d9dfdce-28bc-411c-a996-229301c6b8e5.png)

**Comment by kgday** [comment] 2021-08-06 06:47
@Chris,
Thanks to your hard efforts, as well as all the other contributors.

**Comment by ChrisPulman** [comment] 2021-08-06 06:56
Thanks, we do our best with the information we have, its hard to cover all the possibilities. 
We have been trying to add more tests into ReativeUI and related projects to ensure that these issues are avoided. The more snippets we have of different use cases the easier it is to build tests to ensure we maintain compatibility. 
There will always be a point when something has to change or perhaps even be removed to cater for external changes.

**Comment by csmager** [comment] 2021-08-06 08:40
This is my issue (which I think *is* with `WhenAny`):

This code, in 14.2, shows no warning that `value` could be `null`, as its type is `string` not `string?` and this code will throw a `NullReferenceException` at runtime.
```csharp
public class ViewModel : ReactiveObject
{
    public ViewModel()
    {
        this.WhenAnyValue(x => x.Prop)
            .Subscribe(value => Console.WriteLine(value.Length));
    }

    public string? Prop { get; set; }
}
```
If I add my own `WhenAnyValue` helper with the correct signature, then I get a warning as expected:
```csharp
public class ViewModel : ReactiveObject
{
    public ViewModel()
    {
        WhenAnyValue(this, x => x.Prop)
            .Subscribe(value => Console.WriteLine(value.Length)); // warning: dereference of a possibly null reference
    }

    public string? Prop { get; set; }

    private static IObservable<TRet> WhenAnyValue<TSender, TRet>(
        TSender? sender,
        Expression<Func<TSender, TRet>> property1)
    {
        return sender.WhenAny(property1, (IObservedChange<TSender, TRet> c1) => c1.Value);
    }
}
```

**Comment by glennawatson** [comment] 2021-08-06 08:47
Already a PR to fix the issue so thanks for the detailed code we will add it to the test.

**Comment by csmager** [comment] 2021-08-06 08:50
Thanks. I've looked at the linked PR and the signatures for `WhenAny` / `WhenAnyValue` are unchanged, so I'd expect the above issue to remain.

**Comment by ChrisPulman** [comment] 2021-08-06 14:04
@csmager I am making the changes in stages to make it simple to manage, thanks for your snippet it helped to understand the issue, it became obvious when put that simply. The original aim was to remove as much as possible the need to use notation (? + !), but the reality is its not quite that simple as issues become hidden.

**Comment by csmager** [comment] 2021-08-06 14:08
Makes sense, thanks! All this was a bit of a learning curve when we turned it on in our codebase.

**Closed** 2021-08-07 22:40 UTC
Labels: bug

**Comment by csmager** [comment] 2021-08-11 13:05
Have updated to 14.3.1 to try this out and everything looks great so far. Thanks @ChrisPulman!
