### ISSUE TITLE
[BUG] Xamarin Linker error with ReactiveUI.Events

### ISSUE THREAD

**Issue by RwSgxx** [reactiveui/ReactiveUI#2083] opened 2019-06-23 09:19 UTC
**Describe the bug**

Updated to the latest Xamrin/XamrinForms and ReactiveUI nugets:
ReactiveUI 9.17.11
ReactiveUI.XamForms 9.17.11
ReactiveUI.Events 9.17.11
Xamarin.Forms 4.0.0.497661

In release with the linker deactivated (set to None), the app compiles and runs but it is huge (80MB).
When compiling in release with the linker set to SdkOnly I get the fallowing error (I did try to add the XamarinForms and ReactiveUI dlls to the linker exclusions but it did not help):

4>(_LinkAssembliesShrink target) -> 
4>  Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2225,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
4>Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2225,5): error MSB4018: Mono.Linker.MarkException: Error processing method: 'System.Void Xamarin.Forms.IShellControllerEvents::<get_HeaderChanged>b__3_1(System.EventHandler)' in assembly: 'ReactiveUI.Events.XamForms.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.IShellController::add_HeaderChanged(System.EventHandler)
4>.Common.targets(2225,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
4>.Common.targets(2225,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
4>.Common.targets(2225,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
4>.Common.targets(2225,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
4>.Common.targets(2225,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
4>.Common.targets(2225,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
4>.Common.targets(2225,5): error MSB4018:    --- End of inner exception stack trace ---
4>.Common.targets(2225,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
4>.Common.targets(2225,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
4>.Common.targets(2225,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.Process()
4>.Common.targets(2225,5): error MSB4018:    at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
4>.Common.targets(2225,5): error MSB4018:    at Mono.Linker.Pipeline.Process(LinkContext context)
4>.Common.targets(2225,5): error MSB4018:    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
4>.Common.targets(2225,5): error MSB4018:    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
4>.Common.targets(2225,5): error MSB4018:    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
4>.Common.targets(2225,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
4>.Common.targets(2225,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Steps To Reproduce**
Already described 

**Expected behavior**
Compile normally with the linker active.

**Screenshots**

**Environment**

- OS:       
- Version   
- Device:   

**Additional context**

**Comment by glennawatson** [comment] 2019-06-23 10:08
Thanks, I got an idea where this one is coming in.

**Comment by glennawatson** [comment] 2019-06-23 10:16
What version of Xamarin are you targeting in your NuGet packages, I suspect this is one of those where the event was removed in later versions.

**Comment by glennawatson** [comment] 2019-06-23 10:20
As per our official policy we are always one version behind the latest official version. See https://github.com/reactiveui/rfcs/issues/7

You can however get around this by using the same technology we use to generate the events, and add a NuGet reference to `Pharmacist.MsBuild` and `Pharmacist.Common`

```xml
<ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="3.6.*" />
    <PackageReference Include="Pharmacist.MsBuild" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="Pharmacist.Common" Version="1.*" />
</ItemGroup>
```

This is not a bug so closing the issue.

Thanks for the report.

**Closed by glennawatson** 2019-06-23 10:20 UTC
Labels: bug

**Comment by glennawatson** [comment] 2019-06-23 10:23
btw with pharmacist it has to be in the same project where you reference Xamarin.Forms , it will generate events for any NuGet packages explicitly set in that project. That way you can get events for the new shell stuff etc as well if you want it.
